youngtae/week1/Week1_2573.java, youngtae/week1/Week1_4963.java, youngtae/week1/Week1_7569.java
> 권영태
> 4963(섬의 개수)
>> 섬의 경로를 찾은 것이 아닌, 모든 경로를 탐색해 총 섬의 개수를 파악하는 문제. 
하나의 섬에서 주변 섬을 탐색하는 방법으로 BFS로 풀이 선택.
> 7569(토마토)
>> 익은 토마토에서 주변(상하좌우)를 탐색하며 익지 않은 토마토를 하루마다 익도록 하는 문제.
입력 시 익은 토마토 위치를 기억(`Queue.add(익은 토마토 위치)`시키고, 이를 전염 전 익은 토마토 개수(`q.size()`)만큼 반복해 BFS()를 통해 토마토를 익게 한다.
> 2573(빙산)
>> 토마토 문제와 비슷하게 1년 마다 주변 바다 개수만큼 빙산을 녹여 빙산이 두 덩어리가 되는 해를 찾는 문제.
입력 시 빙산의 위치를 기억(`Queue.add(빙산 위치)`시키고, 이중 BFS()를 통해 빙산 덩어리 개수 확인 + 빙산 녹이기 조합으로 진행하면 된다.
**단, 빙산을 녹일 때 주변 바다 개수만큼 바로 녹이게 되면 바깥쪽 빙산이 먼저 녹아 안쪽 빙산이 녹게 되는 문제가 발생한다.**
그래서 빙산 녹일 값이 담겨진 배열`tmp[][]`를 통해 전체 빙산의 녹일 값을 계산 후 빙산을 한번에 녹여야 한다.
=> [Week1] 권영태

kijung/week1/Week1_2573.java, kijung/week1/Week1_4963.java, kijung/week1/Week1_7569.java
> 박기정
> 2573 빙산
맵을 전부 다 탐색하기보다 빙산의 좌표들을 따로 저장하여 그 좌표들만 탐색하고자 하였습니다.
- Pos 객체를 저장하는 set을 탐색하며 set의 첫 좌표를 DFS로 탐색하였습니다.
첫 좌표만 사용해도 되는 이유는 두 덩이 이상으로 분리되는 것만 확인하면 되기 때문입니다.
한 덩이라면 첫 좌표로 탐색한 빙산의 좌표 수가 전체 빙산의 좌표수와 같아야 합니다. 다를 경우 두 덩이로 분리된 것입니다. 
- 만약 좌표수가 같다면 좌표들을 탐색하며 높이를 바꿔줍니다. 맵의 상하좌우를 탐색했을 때 나오는 0의 개수만큼 감소합니다.
높이를 다 바꿔준 이후 높이가 0 이하가 된다면 set에서 제거 후 맵에 반영하였습니다.
> 4963 섬의 개수
빙산과 마찬가지로 좌표들을 따로 저장하여 좌표들만 탐색하고자 하였습니다. 
다만 이번에는 class 대신 배열로 좌표를 저장하였습니다.
- visited 배열을 사용하여 좌표들의 중복 탐색을 방지하였습니다. 
만약 방문했던 좌표라면 생략하여 BFS를 생략, 방문하지 않았다면 개수를 증가시키며 BFS로 방문처리를 해주었습니다.
>7569 토마토
한번 영향을 미쳤던 토마토는 그 이후에는 다시 영향을 미치지 못하기 때문에 토마토의 좌표들을 별도로 저장하였습니다.
다만 날짜별로 익는 토마토는 다르기 때문에 BFS에 사용될 큐를 전역 변수로 사용하여 좌표들을 큐에 저장하였습니다.
- 첫 큐의 사이즈만큼만 BFS를 작동시키면 같은 날짜의 토마토만 큐에서 빠지게 됩니다. 
이를 적용시키지 않으면 다른 날짜의 토마토도 같이 익게 됩니다. 
만약 이것이 싫다면 별도의 …
=> [week1] 박기정

src/yeoeun/week02/Week2_1149.java, src/yeoeun/week02/Week2_12865.java, src/yeoeun/week02/Week2_2156.java
> 양여은
> ### 1149. RGB거리
- N번째 집이 각각 빨/초/파로 칠해졌다는 가정하에, 각각의 Max 비용을 저장하였습니다.
- 예를 들어, N번째 집이 빨간색이라면, N-1번째 집이 초/파로 칠해졌을 때의 최대 비용 중 Max 값을 채용하였습니다.
> ### 12865. 평범한 배낭
1. i번째 물건을 넣는 경우
: j - i무게 kg을 i-1개의 물건으로 채웠을 때 얻을 수 있는 최대 value + i의 value
2. i번째 물건을 넣지 않는 경우
: j kg을 i-1개의 물건으로 채웠을 때 얻을 수 있는 최대 value
+) 배낭 문제는 풀이를 참고하여 풀었습니다.
> ### 2156. 포도주 시식
- 경우의 수를 5개로 나눠서 생각하였습니다.
- i-2부터 i번째 까지의 포도주를 마시면 o, 안마시면 x로 상정하여 필드명을 지정하였습니다.
* 고려하지 않은 케이스들
ooo → 불가능
xxx → xox가 무조건 더 많이 마실 수 있음
xox → oxo에서 처리 가능
* 고려한 케이스들
oox → i-1, i-2번째를 마시기 위해서는 i-3번째를 마실 수 없음, 경우의 수 하나
oxo → i-1은 안마시니 고려X, i-2를 마시는 경우 중 최대 + i번째 마심
xoo → i-1 마시는 경우 중 i-2 안마시는 경우들 중 최대 + i번째 마심
xxo → i-1번째 안마심, i-2번째 안마시는 경우 중 최대 + i번째 마심
oxx → i-1번째 안마심, i-2번째 마시는 경우 중 최대
=> [week2] 양여은

src/yeoeun/week03/Week3_1647.java, src/yeoeun/week03/Week3_1717.java, src/yeoeun/week03/Week3_24542.java
> 양여은
> 1647: 도시 분할 계획
- 간선 정보를 cost 순으로 관리하는 PriorityQueue와, 각 루트(그래프)별 총 노드 수를 관리하는 Map을 사용하였습니다.
- cost가 낮은 간선부터 가져와, 해당 간선의 양 끝 노드가 연결되어 있지 않은 상태라면 이를 연결하는 작업을 반복함으로써 MST를 구성하였습니다.
- 마을이 2개이고, 두 그래프의 노드 수의 합이 N과 같다면 분리 완료이므로 나머지 edge를 계산하지 않고 계산을 종료합니다.
> 1717: 집합의 표현
- command가 0인 경우에는 두 그래프를 합치는 union()을 실행
- command가 1인 경우에는 각각의 루트를 find()를 통해 찾아 비교
> 24542: 튜터-튜티 관계의 수
- 각 루트(그래프)별 총 노드 수를 관리하는 Map을 사용하였습니다.
- 엣지에 대해 연결 연산을 모두 수행한 후, 최종적으로 Map에 남아 있는 values 값들을 모두 곱해 경우의 수를 도출하였습니다.
=> [week3] 양여은

src/youngtae/week3/Week3_1647.java, src/youngtae/week3/Week3_1717.java, src/youngtae/week3/Week3_2225.java, src/youngtae/week3/Week3_24542.java
> 권영태
> 2225(DP/ 금주 스터디 풀이 문제)
>> 풀이 당일 점화식을 답안과 비슷하게 헀는데 `시간 쫓김 + 갑자기 대충 생각함` 때문에 뭔가 잘못 틀어져서 아쉬움.
>> 이전 DP 배낭문제와 유사한 풀이가 가능하다는 설명을 듣고 풀이 진행
> 1647(도시 분할 계획)
>> 유니온 파인드 문제라고 생각하고 문제를 읽으니 합치는건 할 수 있는데 어떤 기준으로 나눠야할지 감이 안잡혀서 문제 유형 확인해보니, MST 알고리즘 유형이었음.
그래서 MST 알고리즘 개념을 학습한 한 후 다시 보니, 최소 신장 트리에서 가장 마지막에 이어진 간선이 MST의 최대 간선 값임. 그래서 MST를 만들 때 `V(정점) - 1`이 아닌 `V-2`를 통해 마을을 2개로 분리하면 최소값을 얻을 수 있음을 파악하여 풀이함.
> 1717(집합의 표현)
>> 0이 입력되면 union-find를 진행하고 1이 입력되면 find를 통해 같은 집합인지 확인하는 방식으로 간단하게 풀이
> 24542(튜터-튜티 관계의 수)
>> union-find를 한 후 모든 집합을 조합(총 경우의 수)을 뽑아서 출력하면 되겠다 싶었음.) 1~N까지 자신 집합의 최상위 부모를 뽑아서 `Set`에 넣은 뒤 집합들으 모아서 집합의 크기를 곱하면 될 줄 알았는데, 특정 케이스에서 오류가 났었음.
그래서 다른 방식으로 union-find 후 집합의 크기를 저장하는 새로운 배열(`answer[]`)을 만들어서 `1~N`까지 자신 집합의 부모 크기만큼 더해줘서 계산.
근데 왜 2번 나눠야만 답이 되는지 모르곘음..(1번만 나눠도 되나..?)
> 리뷰어가 …
=> [week3] 권영태

src/yeoeun/week04/Week4_15565.java, src/yeoeun/week04/Week4_22945.java, src/yeoeun/week04/Week4_7795.java
> 양여은
> 7795: 먹을 것인가 먹힐 것인가
- 두 배열을 정렬한 후, 각각의 포인터를 관리하였습니다.
- ap번째보다 bp번째가 더 크거나 같으면 bp의 값을 더해주었습니다. (이전의 것들은 모두 ap번째보다 작으므로)
- 만약 bp가 M과 같아진다면, 배열전체가 ap보다 작은 것이므로 count에 M을 더해주었습니다.
> 15565: 귀여운 라이언
- Deque를 활용하였습니다.
- 입력을 받는 동시에, 값이 2면 무시, 1이면 연산을 수행하였습니다.
- 덱의 크기를 K로 제한하고, K+1이 되는 순간 minSize 확인 & poll()을 수행하였습니다.
> 22945: 팀빌딩
- 각 사람에게 들어온 순으로 idx 값을 부여하고, 능력치(cost)를 기준으로 정렬하였습니다.
- 능력치가 작은 순대로, 해당 사람의 능력치가 min이 되는 경우의 max를 구하는 방식을 사용하였습니다. → max = 현재 사람의 cost * 최대 distance
- i-1번째는 i번째 사람과 쌍이 될 수 없으므로, used 배열을 통해 사용 가능한 값을 관리하였습니다.
- pf, pl이라는 포인터를 통해 사용 가능 idx의 양 끝단을 관리하였습니다. 현재사람의 idx와 비교하였을 때 더 먼 것을 채택함으로써 maxDistance를 구하였습니다.
=> [week4] 양여은

src/heejin/week5/Week5_10330.java, src/heejin/week5/Week5_11000.java, src/heejin/week5/Week5_15903.java
> 김희진
> 15903 카드 합체 놀이
- 연속적으로 더한 값이 최소가 되어야하므로, 가장 작은 값부터 더해야 함
- 우선순위 큐를 이용해 입력을 받아, 작은 값이 우선순위가 높도록 저장
- 우선순위 큐에서 값을 두 개씩 꺼내가며 M번 덧셈 수행
- 모든 카드 값 더하여 점수 계산
(Long 타입 안 해서 계속 틀린 악몽의 문제..)
> 11000 강의실 배정
- 시작 시간이 빠른 순으로 정렬 (같으면 종료 시간 빠른순)
- 앞서 정렬한 리스트에서 첫 원소의 종료 시간만 우선순위 큐에 삽입(종료 시간이 빠른 순)
- 큐에는 각 강의실별 마지막 강의 종료 시간이 들어가 있음
- (아직 강의실이 결정 되지 않은 강의들 중 시작 시간이 가장 빠른 강의)를 (강의실이 결정된 강의들 중 종료 시간이 가장 빠른 강의)와 동일한 강의실에 넣는 게 최선의 선택
> 10330 비트 문자열 재배열하기
- 정답 배열은 0으로 시작하거나 1로 시작하거나 두 경우 밖에 없으므로 두 가지의 정답 배열 생성
- 정답 배열과 기존 배열의 원소를 하나씩 비교하며 최소 연산 수 계산
- 만약 원소가 일치하지 않으면 기존 배열에서 일치하는 값을 찾을 때까지 뒤로 이동
- ex. 기존 배열 0, 정답 배열 1 불일치 발생 -> 기존 배열에서 1을 찾을 때까지 다음 인덱스로 이동
- 원하는 값을 찾으면 해당 값을 변경(스왑 의미)
- ex. 기존 배열에서 1을 찾으면, 해당 값은 0으로 변경 
- 만약 원하는 값을 찾지 못했으면, 정답 배열을 만들 수 없음을 의미
- 0으로 시작 or 1로 시작 정답 배열 중 더 작은 연산 값을 출력
=> [week5] 김희진

src/kijung/week5/Week5_10330.java, src/kijung/week5/Week5_11000.java, src/kijung/week5/Week5_15903.java
> 박기정
> 10330번 비트 문자열 재배열하기
- 시작이 1인 목표 배열과 시작이 0인 목표 배열 만들기
- 맨 앞에서부터 목표 배열 숫자로 변경시키며 변경 횟수 증가시키기
- 바꾼 숫자 배열이 목표 배열과 일치하는지 확인
- 일치할 경우 정답 갱신
> 11000번 강의실 배정
- 강의 Class 별도 생성
- 우선순위 큐 사용 (시작 시간이 빨라야 함. 시작 시간이 같은 경우 빨리 끝나는 것 선택)
- 큐에서 하나씩 꺼내며 끝나는 시간을 시작 시간으로 갱신
>15903 카드 합체 놀이
- 더한 값을 우선순위 큐에 넣어줌
- 가장 작은 값만 계속 선택하며 정답 누적시키기
=> [week5] 박기정

src/jinu/week5/Week5_10330.java, src/jinu/week5/Week5_11000.java, src/jinu/week5/Week5_15903.java
> ex) 이진우
문제에서 주어진 조건 그대로 가장 작은 2개를 ```priority_queue``` 의 poll 로 꺼내어 
그 합을 두 번 저장하는 방식으로 문제를 풀이하였습니다.
어려워서 정답 코드를 참조하였습니다. 
먼저 시작 시간 기준으로 정렬하고 PriorityQueue 는 종료 시간 기준으로 만들어서 
지속적으로 PriorityQueue 의 최상단의 값(종료 시간이 가장 작은것) 과 시작 시간을 비교하여 만약 시작 시간이 더 같거나 크다면 
PriorityQueue 에서 해제하고 지속적으로 pq에 종료시간을 추가하여 
추후 PriorityQueue에 남아있는 원소의 개수가 최소 회의실이라는 점을 이용하였습니다.
다시 풀어도 명확하게 척척 진행하지 못할 것 같은 문제입니다.
기존 배열과 임시 배열을  차례로 비교하여 같은 인덱스(i)의 원소가 달라지는 시점이 나온다면 
그 값을 i보다 큰 인덱스에서 swap 하면서 가지고 오는 그림으로 문제를 풀었습니다. 
하지만 이 문제에서 조차 확신이 많이 없었습니다. 
그리디 문제가 
정답 코드 및 해설을 보아도 흠 그런가? 하는 생각이 자꾸 듭니다 .
10330 과 11000 이런 문제들도 리뷰어님은 논리적으로 한 발자국 씩 접근하셨나요?
생각의 흐름이 궁금합니다.
=> [week5] 이진우

src/youngtae/week5/Week5_10330.java, src/youngtae/week5/Week5_11000.java, src/youngtae/week5/Week5_11000_Wrong.java, src/youngtae/week5/Week5_15903.java
>  권영태
> 10330 (비트 문자열 재배열하기)
>> 맨 처음에 `0->1, 1->0`으로 변경하면 되는지 알았던 문제였다. 하지만 예제 출력 값이 너무나 달라서 아님을 알았고,  한칸 한칸 이동시키는 방법임을 알기까지 시간이 걸렸음.  문자열의 시작은 무조건 `0 또는 1`로 시작하기 때문에
그래서 연속코드와 일치하는 문자열 2개(0 시작 || 1 시작)을 만들고 각 문자열의 0과 1의 개수가 본 문자열의 0과 1의 개수와 일치하는지 검증하여 정답 문자열을 찾아낸다.
이후 본 문자열이 정답 문자열로 바뀌기 위해서 몇번의 스왑이 필요한지 계산(ed-st)하여 최소 횟수를 구한다.
> 11000 (강의실 배정)
>> union-find로 각 집합을 만들어서 루트 집합의 개수를 구하면 되겠다고 생각하고 접근했음. 
**하지만 강의 시간의 범위가 `0 ≤ Si < Ti ≤ 10^9` 로 되어 있어서 union-find를 위한 배열 arr의 크기가 너무 커짐 ==> 메모리 초과**
그래서 특정 강의의 종료시간과 시작시간을 잘 연결해서 계산하면 되지 않을까 싶은 접근법을 생각함.
Node 클래스의 comparable를 `o1.end -o2.start` 이런 식으로 구현해서 시도해봤는데 원하는대로 잘 이루어지지 않았음 😢 
어떻게 하면 될지 고민하다가 힌트(정답)을 확인하였음..
오름차순 시작시간 순(같다면 종료시간 순)으로 정렬시킨 강의 시간 배열을 우선순위 큐 `pq`에  모든 강의의 종료 시간을 하나씩 넣으면 된다.
이때 강의 종료 시간을 넣기 전, 해당 강의 시작 시간이 이전 강의의 가장 빠른 종료 …
=> [week5] 권영태

src/heejin/week6/Week6_11559.java, src/heejin/week6/Week6_13164.java, src/heejin/week6/Week6_17142.java, src/heejin/week6/Week6_9519.java
> 김희진
> 13164 행복한 유치원
- 앞 뒤 간격을 diff 배열에 저장한다.
- 간격을 기준으로 오름차순으로 정렬한다.
- K개의 그룹을 만들기 위해서는 N-K번 합치면 된다.
- ex) N=5, K=2일 때 (1,4)로 나누든 (2,3)으로 나누든 3번을 합치면 된다.
- 합친다 = 같은 그룹으로 만든다
> 9519 졸려
- 거꾸로 섞다 보면 다시 처음 단어로 돌아오게 되므로, 주기를 찾을 때까지 거꾸로 섞는 과정을 반복한다.
- 거꾸로 섞는 방법은 다음과 같다.
- 홀수 번째 글자는 순서대로 앞으로 온다.
- 짝수 번째 글자는 거꾸로 뒤로 온다.
- ex) acefdb -> 홀수번째 글자 aed + 짝수번째 글자 거꾸로 bfc => aedbfs
- 거꾸로 섞은 결과가 처음 단어와 동일하다면, 주기가 끝난 것이다. 
- 주어진 X를 주기(rule의 크기)로 나눈 값을 인덱스로 하여 답을 찾는다.
> 11559 Puyo Puyo
- 한 라운드에서 제거될 수 있는 뿌요를 bfs를 사용해 찾는다.
- 각 bfs함수는 시작점을 기준으로 주변에 동일한 색의 뿌요가 몇 개 인지 반환한다.
- 만약 동일 색의 뿌요가 4개 이상이라면 해당 범위는 제거될 수 있다.
- 이번 라운드에서 제거 가능한 뿌요가 없다면 게임을 종료한다.
- 그렇지 않다면 한줄 씩 빈칸 위에 있는 뿌요가 아래로 떨어진다.
- 각 줄의 아래부터 빈 칸을 찾는다.
- 그 위의 빈 칸이 아닌 시점을 찾고, 해당 값을 이전에 찾은 빈 칸으로 옮긴다.
> 17142 연구소 3
- 입력을 받으며 바이러스 위치와 빈 칸 개수를 저장한다.
- 빈 칸이 …
=> [week6] 김희진

src/yeoeun/week06/Week6_11559.java, src/yeoeun/week06/Week6_17142.java, src/yeoeun/week06/Week6_9519.java
> 양여은
> 9519 : 졸려
- X번 되돌리기 로직을 수행하였습니다. 단, 되돌리는 과정에서 첫번째 String과 동일한 문자열이 등장한다면, 더 이상의 탐색을 그만하고 index를 통해 X번 후의 결과를 구했습니다.
- 되돌리는 로직: 짝수번째는 앞으로, 홀수번째는 뒤로 보내는 방식으로 복원하였습니다.
> 11559 : Puyo Puyo
- 먼저, 전체 puyo들에 대해 bfs를 통한 터트리기 작업을 수행하였습니다. 이 과정에서 한 세트라도 터졌다면 다음 회차를 수행하게 됩니다.
- bfs: 현재 뿌요 기준으로 상하좌우를 검사하며, 미방문&&같은 색상의 뿌요가 있다면 확장됩니다. 이때, 확장되는 뿌요 리스트를 관리하여, 4개 이상 터진 경우 일반 배경값인 “.”으로 값을 바꿔주었습니다. 이 경우에만 터짐여부=true를 반환하게 됩니다.
- 만약 다음 터트리기 작업이 필요하다면, 뿌요들을 아래로 내리는 작업을 수행합니다. 세로를 기준으로 맨 아래칸부터 탐색하며, 뿌요보다 아래에 .이 있다면 자리를 바꿔주는 연산을 수행하였습니다.
> 17142 : 연구소 3
- 입력받으며 virus 좌표들을 따로 list로 관리하였습니다. 이후, 백트래킹을 통해 M개 만큼의 활성화 바이러스를 정하고, 각 경우 확산 시간을 bfs를 통해 계산하였습니다.
- 빈칸의 개수를 함께 관리하여, 바이러스가 전체적으로 확산되었는지 여부를 확인하였습니다.
=> [week6] 양여은

src/jiyeon/week7/boj_17940.java, src/jiyeon/week7/boj_20160.java, src/jiyeon/week7/boj_31938.java
>황지연
_모든 문제의 구현 설명은 코드 내 주석으로 달아두었습니다!_ PR에는 문제 접근 로직만 작성하였습니다.
> **17940번 지하철** 
이 문제의 핵심은 무조건 최단 경로를 구하는 것이 아니라, "환승 횟수를 최소로 하는 경로 중" 최단 경로를 구하는 것이다.
이를 고려해주기 위해 최소 비용 갱신 테이블을 i x 2 크기의 배열로 만들어
- dist[i][0] :  출발지에서 i 번째 역으로 가는 최소 환승 횟수
- dist[i][1] : 출발지에서 i 번째 역으로 가는 최소환승 횟수 중 최소 비용
을 저장하도록 하였다. 
이후 다익스트라 메서드에서 탐색을 할 때, 
1. 환승 횟수가 기존 보다 적다면 무조건 dist 테이블 갱신 
2. 만약 환승횟수가 같을 경우에는 최소비용인 쪽으로 갱신 해주었습니다.
----
>
> **20160번 야쿠르트 아줌마 야쿠르트 주세요**
>
>
이 문제의 핵심은 야쿠르트 아줌마는 무조건 주어진 경로를 따라가야하는 반면, 나의 경우에는 출발지에서 바로 해당 목적지까지 가도 된다는 것이다. 
또한, 문제 풀이 할때 주의할 점이 있는데 
1.  아줌마는 주어진 경로를 따라가지만, 다음 목적지로 이동할 수 없으면 그 다음 목적지로 건너뛴다는 것이다. 
- 이 경우 아줌마의 출발지를 갱신하면 안된다. 🥲 이걸 고려 안해줘서 좀 틀렸다.
2. 내가 가는 시간이 아주머니보다 더 빠르거나 같으면 해당 번호가 정답인데, 그런 번호가 여러 개이면 제일 작은 번호를 반환하는 것이다.
- 이 조건 떄문에 중간에 break를 할 수 없고 무조건 경로를 다 돌려봐야한다...
3. 아줌마의 …
=> [week7] 황지연

src/yeoeun/week07/Week7_17940.java, src/yeoeun/week07/Week7_20160.java, src/yeoeun/week07/Week7_31938.java
> 양여은
> 🚉 17940 : 지하철
- Node 객체에 transfer이라는 정보를 추가하여 환승 횟수 정보를 관리하였습니다.
- 현재 역과 다음역이 다른 경우 transfer 값을 1씩 증가시켰습니다.
- PQ에서는 먼저 transfer 횟수를 기준으로 비교하고, 동일하다면 cost를 비교하도록 우선순위를 재설정하였습니다.
> 🧃 20160 : 야쿠르트 아줌마 야쿠르트 주세요
- 다익스트라 호출 횟수를 줄이기 위해, 탐색이 일어난 경우의 시작노드-distance[] 정보를 Map으로 관리하였습니다. 만약 출발노드가 map에 있다면 탐색을 하지 않고, 없는 경우에만 탐색을 하게 됩니다.
- 먼저, ‘나’의 각 노드까지의 거리를 계산하여 map에 등록합니다.
- 야쿠르트 아줌마: 시작 노드를 기준으로 다익스트라를 시행합니다. 이후, 도착 가능한 가장 가까운 지점을 계산합니다. (INF가 아닐때까지 i 증가)
- 각 경우 ‘나’와 만나는 것이 가능한지 계산 후 min 노드 번호를 구합니다.
> 🛻 31938 : 현대모비스 트럭 군집주행
- 한 번 사용된 도로는 90%가격으로 사용할 수 있다고 볼 수 있습니다. 즉, N번 노드까지의 최종 비용은 (이전 노드까지의 거리 * 0.9 + 마지막 경로 거리)이 됩니다.
- 최소 비용이 아닌, 최소 거리를 기준으로 트럭이 이동하기 때문에 기존 거리 정보를 기준으로 최단 경로를 탐색합니다.
- 단, distance는 같아도 비용이 다른 경우가 존재하기 때문에 새로운 distance가 기존의 distance와 같은 경우에도 answer 업데이트 로직을 실행합니다.
- …
=> [week7] 양여은

src/jinu/week7/Week7_17940.java, src/jinu/week7/Week7_20160.java, src/jinu/week7/Week7_31938.java
> ex) 이진우
- 다익스트라에서 PQ 를 활용
- PQ 는 환승횟수가 적은 것, 환승 횟수가 같다면 비용이 작은 것을 꺼내오도록 사용 
-  dist[i] : 출발점 부터 i 까지 갔을 때 최소 시간비용 , transferNum[i] : 출발점 부터 i까지 갔을 때 최소 환승 횟수 를 관리하여 다익스트라 과정 중 갱신이 용이하게 함.
- 다익스라에서 PQ를 활용
- PQ는 비용이 제일 작은 것을 우선으로 둠
- 요구르트 아줌마의 판매 경로 배열을 저장한 이후, 특정 지점마다 몇초에 도착하는지 다익스트라를 활용하여 계산 
- 나의 위치에서 요구르트 아줌마의 방문 위치까지 걸리는 시간을 찾은 이후 그 값이 요구르트 아줌마가 걸리는 시간보다 작거나 같으면 그 INDEX 를 기록하여 최솟값을 구함.
- 다익스트라에서 PQ를 활용
- PQ는 기본적으로 최단 거리가 짧은 순 , 최단거리가 같다면  그 노드까지의 시간비용이 더 짧은 것을 선택
- PQ 과정에서 특정 노드가 선택되었을 때 그 이전 노드를 함께 저장할 수 있게 하기위해 Node 에 from 값을 추가하였으며, 
이전 노드의 index 를 저장하기 위해 path 배열 사용 
- path 배열을 사용하여 timeGraph 초기화// timeGraph[3].add(5) 의 의미는 5의 이전 노드는 3이다. (이전 노드란 1->... i,i+1)이라면 i+1의 이전 노드는 i )
- 추후 이 timeGraph 를 BFS로 탐색하여 값을 계산 및 저장 . 
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 …
=> [week7] 이진우

src/youngtae/week7/Week7_17940.java, src/youngtae/week7/Week7_20160.java, src/youngtae/week7/Week7_2072.java, src/youngtae/week7/Week7_31938.java
> 권영태
> 2072 (오목)
>> 게임이 끝날때까지 흑, 백을 순서를 바꿔가면서 돌을 하나씩 놓고 놓을때마다 4가지( 가로, 세로, 대각선 2방향) 방향으로 확인해서 오목을 확인한다. 단 확인시 6목 이상인지 주의해서 확인한다.
> 17940 (지하철)
>> 환승이 최단 횟수라면 거리(비용)값은 신경쓰지 않는다. 하지만 환승 횟수가 동일하다면 거리(비용)가 최소인 곳으로 가야하도록 구현.
> 20160 (야쿠르트 아줌마 야쿠르트 주세요)
>>  주어진 그래프에 따라 내가 갈 수 있는 최단경로(다익스트라2)와 야쿠르트 아줌마가 st -> ed로 이동하는 최단 비용을 구하며 비용을 비교해 마주칠 수 있는 정점의 최소 정점 번호를 출력시킨다. 여기서 주의할 점은 st -> ed로 이동하는 경우가 중복으로 나올 수 있는데 매 번 다익스트라를 통해 구하는게 아니라, 처음 최단 거리를 구한 배열을 저장해놓고 이를 이용해 시간초과를 피해야한다.
> 31938 (현대모비스 트럭 군집주행)
>> 최단 거리와 최단 비용은 다르다. 이를 주의하고 풀어야 하며 트럭이 이동하는 최단 거리(`Path[]`)를 통해 할인된 비용을 더해 결과를 구한다.
또한 최소 비용은 실제 거리가 같아도 비용이 달라질 수 있기에 if절을 하나 더 검증해 진행해야 시간초과가 발생하지 않는다.
=> [week7] 권영태

src/heejin/week8/Week8_1477.java, src/heejin/week8/Week8_17951.java, src/heejin/week8/Week8_32718.java
> 김희진
> 1477 휴게소 세우기
- 휴게소가 없는 최대 거리의 최소값은 0, 최대값은 L-1 (끝에는 휴게소 세울 수 없으므로)
- 최대 거리의 최소값이므로 lower bound 구하기
- 최대 거리가 mid일 때 설치 가능한 휴게소 개수 구하기
- 휴게소 개수가 M개보다 많으면 최대 거리 늘리기
> 17951 흩날리는 시험지 속에서 내 평점이 느껴진거야
- 시험 점수 최소값은 0, 시험 점수 최대값은 모든 점수 합했을 때
- 최소값의 최대를 구하는 것이므로 upper bound 구하기
- 시험 점수가 mid일 때 나눌 수 있는 그룹 수 구하기
- 그룹 수가 K이상이면 시험 점수를 더 높여보기
> 32718 우선순위 큐와 시뮬레이션
- (원소 + sumA) % K 가 최대 = (원소 + sumA) 가 K 미만이면서 최대인 값 = 원소가 K-sumA 미만이면서 최대
- 일단 lower bound로 K-sumA 이하의 최대값 구하기
- 그리고 이하를 미만으로 만들기 위해 -1 하기
-  이때, 0일 경우는 -1하면 인덱스 범위 초과이니, 원형으로 돌아서 N-1이 됨
- 구한 인덱스의 원소 + sumA %K 를 출력하기
=> [week8] 김희진

src/yeoeun/week08/Week8_1477.java, src/yeoeun/week08/Week8_17951.java, src/yeoeun/week08/Week8_32718.java
> 양여은
> ### 1477 : 휴게소 세우기
- 1 ~ L-1 범위 내의 거리 중, 최대 거리(mid)를 탐색합니다.
- N개의 휴게소 사이를 mid로 나누었을 때 두 휴게소 사이에 새롭게 세울 수 있는 휴게소의 개수를 구할 수 있습니다.
- 이들을 전부 더했을 때 M개보다 많다면 거리를 증가시키고, 아니라면 거리를 감소시켜 최대 거리를 구합니다.
> ### 17951 : 흩날리는 시험지 속에서 내 평점이 느껴진거야
- 매개변수 탐색을 위한 최소를 가장 작은 수, 최대를 전체 총합으로 설정합니다. 여기서 mid는 최소 점수의 합(각 그룹의 총합은 mid보다 커야함)이 됩니다.
- 점수들을 차례대로 조회하며 더해줍니다. 여기서 합이 기준보다 크거나 같으면 그룹 수를 증가시키고, 다시 0부터 시작해 뒤의 점수들을 더해줍니다.
- 결과로 나온 그룹의 수를 기준으로 최소/최대 값을 갱신시켜줍니다.
> ### 32718 : 우선순위 큐와 시뮬레이션
- 큐의 숫자(nums)들을 입력 받을 때 %K로 초기 설정을 해줍니다.
- 더해야하는 수(A)를 입력받을 때,  기존의 수에 새로운 수를 더해주고 %K를 해줍니다. (A + B) % K + C % K == (A + B + C) % K의 원리를 이용하였습니다.
- 만약 nums에 새로운 수 A를 더했을 때 K보다 크거나 같다면, 그 수는 반드시 A보다 작아지게 됩니다. 반면, nums[i]+A < K 라면 그 수는 반드시 A보다 커집니다. 따라서, nums[i]가 K-A보다 작은 수 중 가장 큰 수를 구하고, 거기에 A를 더한 값이 top이 됩니다.
- 이분 탐색 …
=> [week8] 양여은

src/youngtae/week8/week8_1477.java, src/youngtae/week8/week8_17951.java, src/youngtae/week8/week8_32718.java
> 권영태
> 1477(휴게소 세우기)
>> 문제를 읽자마자 1부터 L사이의 있는 휴게소의 거리 차이를 배열을 만들어서 이분 탐색으로 배열을 탐색하며 결과를 찾으면 되려나 싶었는데, 틀린 풀이였음. 거리 차이를 이용해서 풀면되는건 맞았다고 생각해서 `arr`배열을 사용해서 풀이함. 이분 탐색으로 휴게소가 없는 최대 구간(mid)를 구하고 `arr`배열을 돌며 해당 구간에 몇개를 세울 수 있는지 확인하며 최대 구간(mid)를 구함
> 17951(흩날리는 시험지 속에서 내 평점이 느껴진거야)
>> 그룹을 나누는 모든 경우의 수를 구하려고 백트레킹을 열심히 구현하다 이 방법이 맞는건가 싶었음.. 여은님과 풀이법에 대해 의논하다 이 방법이 아님을 알게 되었고 풀이 설계를 조금 찾아봄.. 평균 점수(mid)를 구해 그룹이 K개가 나오는지 확인하며 최대 점수를 계산하면 되었음.
> 32718(우선순위 큐와 시뮬레이션)
>> 모든 값을 배열에 넣고 더하고, 나누는 계산을 반복하며 정렬을 통해 최대값을 찾아도 되겠다 싶었지만 역시나 시간 초과 발생..
이 문제는 모듈러 연산이 주 메인이고, 이분 탐색이 서브인 문제.. GPT가 풀이해주고 저를 이해시켜줬습니다..
> 이분 탐색은 할만한데 문제를 꼬아서 내니깐 매개 변수 탐색이 진짜 감 잡기 힘드네요.
=> [week8] 권영태

src/kijung/week8/Week8_1477.java, src/kijung/week8/Week8_17951.java, src/kijung/week8/Week8_32718.java
> 박기정
> 1477(휴게소 세우기)
- 매개변수 탐색 문제 (결정 문제. 해당 값에서 조건을 만족하는가?)
- cnt <= M을 만족하는 최소의 mid를 찾는 것이 목표
- 각 휴게소 간격을 확인하며 gap / mid를 계산해 추가해야 할 휴게소 개수를 결정.
- gap % mid == 0인 경우 중복 설치를 방지하기 위해 cnt--를 수행.
> 17951(흩날리는 시험지 속에서 내 평점이 느껴진거야)
- 매개변수 탐색 문제 (마찬가지로 결정 문제)
- mid 점수를 기준으로 그룹을 나눌 수 있는지를 확인
- 현재 그룹 점수 합이 mid 이상이 되면 그룹을 나누고, 그렇지 않으면 계속 더하기.
- 최종적으로 나눌 수 있는 그룹 개수를 반환하여 K개 이상의 그룹이 가능한지 확인
> 32718(우선순위 큐와 시뮬레이션)
- 배열 정렬 후 이분 탐색을 활용하여 최적의 값 찾기
- 주어진 수 배열을 정렬한 후, adds 배열(누적된 나머지)을 활용하여 K - offset 이상이 처음 등장하는 위치를 찾기
- 처음 등장하는 위치로 최대값 계산
> 우선순위큐 문제 너무 어렵습니다아아
=> [week8] 박기정

src/yeoeun/week09/Week9_1052.java, src/yeoeun/week09/Week9_10728.java, src/yeoeun/week09/Week9_15661.java
> 양여은
> 1052 : 물병
- 상점에서 물을 사올 수 있기 때문에, 들고갈 수 없는 경우는 존재하지 않습니다. 또한, K 이하의 물통을 들고갈 수 있기 때문에 N ≤ K인 경우에는 0을 출력하고 프로그램을 종료시킵니다.
- 각 물병에는 2의 제곱수만큼의 물이 들어갈 수 있습니다.
- 2의 제곱수 중 남은 물의 양을 넘지 않는 최대의 양을 각 물통에 넣어줍니다.
- 이때, 남은 물이 0이면 새로운 물을 사지 않아도 되므로 0을 출력합니다.
- 만약 0이 아니라면, 남은 물보다 큰 2제곱수 중 최소의 값에서 남은 물을 빼준 양만큼이 필요해집니다.
> 10728 : XOR삼형제 1
- A^ B ^ C == 0이 되기 위해서는, A ^ B == C가 성립해야 합니다. (ABC 순서 무관, 두 값의 XOR이 다른 하나의 값이 되어야 함)
- 비트마스킹의 부분집합 구하기를 활용해 가능한 경우의 수 전체에 대해 탐색을 진행했습니다.
- 부분집합에 A^B == C의 조건을 만족하는 요소가 있다면 다음 부분집합을 확인합니다. 만약 없다면 그 중 최대 길이를 찾아 업데이트합니다.
> 15661 : 링크와 스타트
- 비트마스킹 부분집합 구하기를 활용했습니다.
- 0에 해당하면 스타트, 1에 해당하면 링크 팀으로 구분하였습니다.
- 각 경우의 start/link 점수를 구해 그 중 최소 차가 되는 경우를 구했습니다.
=> [week9] 양여은

src/heejin/week9/Week9_1052.java, src/heejin/week9/Week9_10728.java, src/heejin/week9/Week9_15661.java
> 김희진
> 1052 물병
N을 2진수로 변환했을 때 1의 개수가 만들 수 있는 최소 물병 수라는 것을 알 수 있습니다.
ex. 13 = 1101 -> (8,2,1) 8L, 2L, 1L 물병 3개로 만들 수 있습니다.
그래서 bitCount 함수를 통해 1의 개수를 구하고, 이 값이 K보다 크면 새로운 물병을 구매합니다.
- 새로운 물병 구매 = N에 1L 추가
> 10728 XOR 삼형제1
- 1~N을 수열에 포함하냐 안하냐를 비트 마스킹으로 표시하여 모든 경우를 탐색합니다
- mask값을 결정하고, 이에 따라 수열에 포함되는 숫자를 temp에 담습니다.
- temp에 담긴 값들이 XOR 조건을 만족하고, 현재까지 가장 긴 길이라면 답을 업데이트 합니다
> 15661 링크와 스타트
- N 비트로 각 번째 사람이 스타트팀에 포함되는지(1) 안 되는지(0)를 표시합니다
- 팀에 한 명 이상이어야 하므로 모든 비트가 1인 경우(1<<N - 1) 미만까지 탐색합니다
- mask에 따라 두 팀의 능력치를 계산합니다
- i번째 비트와 j번째 비트 값을 구합니다
- 두 비트를 XOR 했을 때 0이라면 같은 팀입니다
- 따라서 같은 팀인 경우, i번째 비트값에 따라 팀의 능력치를 업데이트합니다
- 능력치를 계산한 후 답을 업데이트합니다 
=> [week9] 김희진

src/jiyeon/week9/boj_1052.java, src/jiyeon/week9/boj_10728.java, src/jiyeon/week9/boj_15661.java
> 황지연
> **1052번 물병**
1리터씩 들어있는 물병을 합쳐서 K개 이하로 만들고 싶다면 물병 개수를 2진수로 만들었을 때의 1의 개수가 K보다 작거나 같으면 된다. 
우리가 어렸을 적 즐겨하던 2048이라는 게임을 떠올리면 이해가 쉬울 것이다.
반복문을 돌면서 1의 개수를 체크한다. 
만약 1의 개수<=K 이면 break; 
아니라면 물병 개수 +=1을 해도 되지만 비효율적
=> 0인 자릿수를 1로 만들어주면 된다. 그러기 위해서는 제일 오른쪽에 위치한 0의 인덱스를 반환 받고, 그 만큼 물병 개수를 더 해주면 된다.
------
> **15661번 링크와 스타트**
링크 팀과 스타트 팀을 나눠주어야한다. 
N<=20이라는 조건이 있기때문에 비트마스킹으로 조합을 구할 수 있다. 
각 인덱스의 위치한 숫자를 해당 사람이 속한 팀이라고 생각하자. (0은 스타트 팀, 1은 링크 팀)
- 예를 들어 사람이 4명인데 1,3번 사람은 스타트팀이고 2,4번 사람은 링크 팀이라면 `1010`으로 표현할 수 있다.
- 여기서 주의할 점은 각 팀에 최소 1명 이상 배치되어야하기 때문에 0000 ... / 1111 ... 과 같이 모든 자리가 0 혹은 1로 이루어져있는 경우는 배제해주었다. 
이후 각 팀의 점수를 계산해주면된다! 끝
-------
> **10728번 XOR 삼형제 1**
비트마스킹으로 완탐하여 풀이하였다.
주요 로직은 다음과 같다.
1. 주어진 N을 입력 받고 1~N 중 3개의 원소를 뽑아 XOR의 결과가 0이면 HashSet에 저장한다.
2. 그 후 1~N 중 모든 원소 수열을 탐색한다. 
3. 수열 …
=> [week9] 황지연

src/youngtae/week9/week9_1052.java, src/youngtae/week9/week9_10728.java, src/youngtae/week9/week9_15661.java
> 권영태
> 1052(물병)
>> 그리디 풀이법
>>> - 같은 크기의 물병만 합칠 수 있음 -> 2의 배수로 나눠지면 합쳐진다.
>>> - 나머지가 존재한다면 남은 물병 증가
>>> ex) 기존 물병 5개 `5%2=1` -> count++, 물병 = 물병 / 2  이를 물병 > 0일때까지 반복하면 2개가 남아서 총 3개를 더 구매해야 된다.
>> 비트마스크 풀이법  * 풀이법 확인
>>> - 1의 개수가 최소로 줄일 수 있는 물병의 개수가 된다. 
>>> - 이를 K개 이하로 만족할 떄까지 물병을 증가시키고, 몇개를 더 증가시켰는지 저장한다.
> 10728(XOR 삼형제1)
>> 비트마스크 풀이법 * 풀이법 확인
>>> 실버 문제부터 도전해봐야겠어서 도전했는데 도저히 모르겠었음.
>>> 맨 처음에 세 원소를 XOR하라고 해서 세 원소를 뽑아 XOR로 검증하고 이를 반복해서 값을 찾았는데 틀림.
>>> 그래서 풀이법을 찾아보고 따라함....
> 15661(링크와 스타트)
>> 백트래킹 풀이법
>>> - 먼저 A팀과 B팀의 위치는 중요하지 않다.
>>> - 즉, 1~N까지 있을 떄 N/2까지만 확인해서 최소 차이를 찾아내면 된다.
>>> - A팀을 기준으로 A팀의 최대 인원을 N-1부터 1까지 줄여가면서 백트레킹을 돌린다.
>>> - A팀 최대 인원만큼 뽑은 뒤에 `boolean[]`을 통해 뽑히지 않은 인원을 찾아낸다.
>>> - 각 팀의 능력치를 계산하고 능력치 차이를 계산 및 최소값과 비교한다.
>> 비트마스크 풀이법  * 풀이법 확인
>>> - 2의 N제곱 만큼 경우의 수가 존재 하지만 이도 팀은 …
=> [week9] 권영태

src/yeoeun/week11/Week11_11657.java, src/yeoeun/week11/Week11_도넛과_막대_그래프.java, src/yeoeun/week11/Week11_주사위_고르기.java
> 양여은
> 타임머신
- N-1번을 돌았는데도 다음에 값이 업데이트되면 음의 사이클(무한히 작아짐) 발생했다는 뜻이됩니다.
- 따라서 N번째에 값이 변경되면 음의 사이클이 발생하였다는 의미이므로 이 경우에는 false를 반환하여 -1을 출력하도록 하였습니다.
- 이외의 경우는 기존의 벨만포드 알고리즘과 동일합니다.
> 도넛과 막대 그래프
- `root`: 진입이 0개임, 막대의 시작도 0이지만 그건 최대 진입이 1개
- `8자`: (중앙)진출이 항상 2개, root와 달리 진입이 존재
- `막대`: (맨끝)진출이 없는 유일한 노드, 단 진입은 반드시 존재
- `도넛`: root의 out 수 == 전체 그래프 수이므로 전체에서 8자&막대를 뺀 나머지
> 주사위 고르기
- 백트래킹을 통해 N/2개의 주사위를 선택해줍니다.
- A,. B 주사위로 나올 수 있는 모든 합의 조합을 각각 구해줍니다.
- A의 각 요소에 대해, 이보다 작은 B의 값의 수를 이분탐색을 통해 구해줍니다.
- 이 중 최대를 계산한 후 반환합니다.
=> [week11] 양여은

src/yeoeun/week14/Week14_n1_카드게임.java, src/yeoeun/week14/Week14_상담원_인원.java, src/yeoeun/week14/Week14_양궁대회.java
> 양여은
> 양궁대회
- 라이언이 이기는 경우와 지거나 비기는 경우, 각각에 대해 dfs를 실행했습니다.
- 마지막까지 화살을 전부 사용하지 못한 경우에는 전체를 0점으로 설정해서 dfs를 실행했습니다.
- 모두 쏘면 점수 계산을 수행합니다.
> n+1 카드게임
- 첫 카드 (n/3)개를 선택합니다. 이후로는 카드가 남아있음 + coin이 남아있으면 라운드마다 2장씩 선택합니다.
- canSelect는 선택 가능한 카드, isFree는 이미 제출한 카드를 의미합니다. 선택 가능한 카드 중 아직 제출하지 않은 카드들 중 n+1이 되는 조합들의 최소 비용을 구합니다.
- 최소인 경우를 선택하고, coin이 필요한 카드가 선택되었다면 coin을 감소시킵니다.
- 다음 라운드로 돌아가 더 이상 뽑지 못하는 경우까지 반복합니다.
> 상담원 인원
- 유형별로 req들을 나눠서 리스트의 리스트 형태로 정리합니다.
- 이후, 특정 타입에 상담원이 ?명일 경우 최소 대기 시간을 구합니다.
- 전체가 1인 경우부터 시작해서, n-k번 동안 대기가 큰 타입에 인원을 증가시켜줍니다.
- 최종 대기 시간을 계산해 반환합니다.
> 프로그래머스 너무 어렵네요 🥹
=> [week14] 양여은

src/yeoeun/week16/Week16_13422.java, src/yeoeun/week16/Week16_20008.java, src/yeoeun/week16/Week16_2987.java
> 양여은
> 2987 : 사과나무
- 나무의 위치 p와, 삼각형의 세 점 중 2개의 위치를 통해 각각 넓이를 구합니다. 결과적으로 나온 3개의 삼각형의 넓이의 합이 땅의 면적과 동일하다면 나무가 땅 내부에 존재한다고 판단할 수 있습니다.
> 13422 : 도둑
- 입력이 들어올 때마다 total을 구하여 K 미만인 경우 정답으로 추가합니다.
- 새로운 입력이 들어오면 total에 더하고, 총 개수가 M개 이상일 경우 이전의 값을 뺌으로써 슬라이딩 윈도우를 구하였습니다. 맨 앞 + 맨 뒤의 조합인 경우를 고려하기 위해 총 N+M-1번 탐색을 진행합니다.
- 단, N==M인 경우, 동일한 선택지를 다른 결과로 판단할 수 있기 때문에 이 경우에는 N번만 검증을 시도합니다.
> 20008 : 몬스터를 처치하자!
- 한 턴이 진행될 때마다 skill의 정보와 HP를 계산하여 백트래킹을 시도합니다.
- 만약 해당 턴에서 사용 가능한 스킬이 없는 경우에는 skill의 leftTime만을 갱신하여 다음 턴으로 이동합니다.
- HP가 0보다 작아지면 최솟값을 비교하여 정답을 갱신합니다.
=> [week16] 양여은

src/jaehyeon/week16/Week16_13422.java, src/jaehyeon/week16/Week16_20008.java, src/jaehyeon/week16/Week16_2987.java, src/jaehyeon/week16/Week16_2987_1.java, src/jaehyeon/week16/Week16_2987_2.java
> 임재현
> [사과나무](https://www.acmicpc.net/problem/2987)
사과 나무 좌표 기준, 3개의 삼각형 꼭짓점으로 선을 이으면 생기는 도형의 넓이를 이용했습니다.
출력값 중 하나인 원래 도형의 넓이와 사과나무 좌표와 삼각형 꼭짓점을 이용해 만든 도형의 넓이가 동일하면 삼각형 내부, 동일하지 않으면 외부에 있는 사과나무라고 판단하였습니다.
소수점 정확도 문제를 해결하기위해 BigDecimal을 사용하였습니다.
다른 풀이를 찾아본 결과, CCW 알고리즘을 이용해서 풀이했습니다.
사과 나무 좌표를 기준으로 각 선분에 대해서 CCW 알고리즘을 돌리고 동일한 시계 방향 or 직선 방향 일 경우 내부, 일치 하지 않는 시계 방향일 경우 외부의 사과나무라고 판단했습니다.
> [도둑](https://www.acmicpc.net/problem/13422)
초기 연산으로 m만큼 집을 털었을 때 얻을 수 있는 금액을 저장한다.
이후 한 칸씩 전진하면서 이전 집은 빼고 추가한 집을 더하는 방식으로 완전 탐색을 진행했습니다.
주의할 점은 n==m 인 경우로 첫 회가 최대 경우의 수일 경우 예외 처리를 해주었습니다.
> [몬스터를 처치하자!](https://www.acmicpc.net/problem/20008)
어떤 스킬을 사용할 지 선택하는 부분을 분기처리, 백트래킹하여 완전탐색을 진행했습니다.
hp가 0이하가 될 때, 이미 최소값을 넘어섰을 때, 로 탈출 조건을 만들었고,
의도치 않은 무한 루프에 빠지지 않게 모든 스킬이 쿨타임인 경우에만 단순 시간 증가 로직이 동작하도록 구현하였습니다.
> 리뷰어가 …
=> [week16] 임재현
