URECA-2nd-study/Algorithm

- yeoeun/week01/Week1_2573.java
- yeoeun/week01/Week1_4963.java
- yeoeun/week01/Week1_7569.java
양여은
> ### 4963 : 섬의 개수
* dfs를 사용하여 checkAround() 메소드가 호출될 때마다 count를 증가시키는 방식으로 구현
> ### 2573 : 빙산
1. 바다 상태를 입력받으며, isMelted 값을 함께 초기화
2. 아래를 반복하며 몇 년이 경과했는지를 count
1. 현재의 얼음 개수를 count (dfs 활용, 2개 이상이면 break 후 2로 반환)
1. 0개 : 다녹을때까지 나눠지지X 경우 → break;
2. 1개: 더 녹여야하는 경우
- 바다 정보는 지속적으로 업데이트되므로, isMelted[][]로 상태 확인
- 주변 바다 개수만큼 감소시키기 (최소 0)
- 1년 경과하면 isMelted값 새롭게 업데이트
3. 2개: 나누어짐 → break;
> ### 7569 : 토마토
1. 토마토 정보를 입력받기
1. 만약 숙성 토마토(1)가 들어온다면 matured 큐에 추가
2. 이와 동시에 flag를 활용해 미숙성 토마토가 없다면 바로 0을 반환 (시간↓용)
2. 덜익은 토마토가 있다면, 숙성일 계산해주는 함수 호출
1. 덜익은 토마토(0)이 없는 경우
1. 전부 익은 경우이므로 바로 count값을 반환
2. 있는 경우
1. matured가 비어있는 경우
- 남은 토마토를 익힐 수 없는 상황 : -1 반환
2. 값이 있는 경우
- 새로 익은 토마토(다음날)을 관리하기 위한 tempQ 활용
- 기존 큐를 돌면서 주변 토마토 검사(BFS), 새로 익은 토마토는 tempQ에 추가
- matured를 tempQ로 초기화
> [week1] 양여은

- minsu/week1/빙산(2573).md
- minsu/week1/섬의 개수(4963).md
- minsu/week1/토마토(7569).md
> 김민수
> 빙산(2573)
맵 크기가 N이면 2차원 배열을 (N+2)(N+2)로 크기를 잡았습니다. 그 이유는 입력 값의 밖 부분은 바다라고 나왔기때문입니다.  bfs탐색을 활용하였으며 bfs 탐색의 시작 지점은 섬인데 배열에서 가장 먼저 나오는 섬으로 시작점을 가졌습니다. 탐색이 끝나면 조건에 맞춰서 섬의 형태를 바꾸고 분리가 되었는지 안되었는지 확인하는 것으로 구성하였습니다.
> 섬의 개수(4963)
입력된 값들 중 ArrayList<int[]>로 받아서 탐색을 진행하였습니다. visited를 활용하여 이어지지 않은 섬들의 갯수를 확인하는 것으로 구성하였습니다.
> 토마토 (7569)
bfs를 활용하여 조건에 맞게 탐색하는 것으로 코드를 구성하였습니다.
>
> [week1] 김민수

- src/heejin/week2/Week2_1149.java
- src/heejin/week2/Week2_12865.java
- src/heejin/week2/Week2_2156.java
- src/heejin/week2/Week2_2668.java
> 김희진
> 2668 숫자 고르기
탐색했을 때 시작점으로 다시 돌아오면 답에 포함
[예제]
1 2 3 4 5 6 7
2 3 1 4 7 7 6
1->2->3->1(O) 답 가능
4->4(O) 답 가능 -> 시작점으로 돌아오면, 탐색 종료 + 시작점이 답에 포함
5->7->6->7(X) 답 불가능 -> 시작점이 아니며 전에 방문했던 곳으로 돌아오면, 그냥 탐색 종료
> 1149 RGB 거리
N번 집의 색에 따른 최소 비용을 구하고, 이 중 가장 작은 비용을 선택
N번 집의 색에 따른 최소 비용 = N-1번 집의 색이 N번 집과 다를 때의 최소 비용 + N번집 색의 비용
(1) N번 집의 색이 빨강이면, 이전 집은 초록 or 파랑
(2) N번 집의 색이 초록이면, 이전 집은 빨강 or 파랑
(3) N번 집의 색이 파랑이면, 이전 집은 초록 or 빨강
> 2156 포도주 시식
N개의 포도주에 대해 최대 포도주 양은, 아래 3가지 케이스 중 하나
(1) (N-3개 중 최대 포도주 양) + (N-1번 포도주 양) + (N번 포도주 양)
(2) (N-2개 중 최대 포도주 양) + (N번 포도주 양)
(3) (N-1개 중 최대 포도주 양)
> 12865 평범한 배낭
i번 물건에 대해 선택지는 두 가지
(1) 물건을 가방에 넣는다
(2) 물건을 가방에 넣지 않는다
남은 최대 무게가 j일 때 i번 물건까지의 최대 가치 합
(1) j < (i번 물건 무게): 가방에 물건을 넣을 수 없으므로 i번 물건을 넣지 않음
(2) j >= (i번 물건 무게): (i번 물건을 가방에 안 넣는 경우), (i번 물건을 가방에 넣는 경우) 중 …
> [week2] 김희진

- src/jiyeon/week2/boj_1149.java
- src/jiyeon/week2/boj_12865.java
- src/jiyeon/week2/boj_2156.java
- src/jiyeon/week2/boj_2668.java
황지연
> 1149번 RGB 거리
dp의 정석같은 문제라 어렵지 않게 풀었습니다. 
dp[i][n] 배열을 i번째 집을 색깔 n으로 칠했을 때의 최소 비용 누적 합으로 정의하고 점화식을 세웠습니다.
dp[i][n] = dp[i-1][n]을 제외한 dp[i-1]의 요소 값 중에 MIN 값 + cost[i][n];
> 2156번 포도주 시식
점화식을 세우는데 꼬박 하루 반이 걸렸던 문제입니다...🥲
연속 3잔을 마실 수 없다는 제한 조건이 걸려있기 때문에, 
dp[i] : 1~i번째 포도주까지 주어졌을 때 최대로 많이 마실 수 있는 포도주의 양으로 정의를 하고, 점화식에서 dp[i-3]~dp[i-1]까지 고려하는 방식으로 접근하였습니다.
_자세한 점화식 도출과정은 코드에 주석으로 적어놓았습니다._
> 12865번 평범한 배낭
배낭 문제 같은 경우에는 최대한 DP 문제의 개념을 생각하며 점화식을 도출하였습니다. 
dp 문제는 큰 문제를 작은 문제로 쪼개고, 작은 문제를 메모화하여 큰 문제를 풀 때 사용하는 방식으로 주로 사용되는 것이라 알고있기 때문에 해당 개념을 생각하며 점화식을 도출하려고 노력하였습니다.
처음에 dp배열을 정의하는 것이 좀 어려웠는데 포도주 문제와 비슷하다 생각이 들어 유사하게 작성해보았는데 맞았습니다..ㅎ
_자세한 점화식 도출과정은 (노가다.ㅎ) 코드에 주석으로 작성하였습니다._
> 2668번 숫자고르기 
제가 생각한 의사 결정 코드는 다음과 같습니다.
1. 문제에서 주어진 숫자 배열을 연결 리스트를 이용하여 <그래프>로 만든다.
2. 그래프를 탐색하는 dfs 함수를 만들고 해당 그래프가 …
> [week2] 황지연

- src/kijung/week3/Week3_1647.java
- src/kijung/week3/Week3_1717.java
- src/kijung/week3/Week3_24542.java
> 박기정
> 1647: 도시 분할 계획
- 마을을 2개로 나누면서 최소 비용으로 연결하는 것이 핵심
- 최소 비용으로 모든 마을을 연결 후 그 중 가장 큰 비용의 간선만 제거하면 문제의 조건을 만족시킬 수 있음.
> 1717: 집합의 표현
- Union-Find의 기본 메소드만 구현하는 문제
- 입력값 a에 따라 union과 find를 나눠서 실행
> 24542: 튜터-튜티 관계의 수
- 멘토의 수를 확인하기 위해 Map 사용
- 멘토별 숫자의 곱을 통해 답을 도출
> [week3] 박기정

- src/minsu/week3/BOJ_1647.java
- src/minsu/week3/BOJ_1717.java
- src/minsu/week3/BOJ_24542.java
> 김민수
> 24542번 (튜터-튜티 관계의 수)
주어지는 입력에 값에 맞춰서 각각의 집합을 만들었고 집합의 원소 갯수 만큼 경우의 수가 생기기 때문에 각 집합의 경우의 수를 곱해주면 출력 값이 나옵니다.
> 1717번 (집합의 표현)
0일 때, 합집합이며 합집합은, 해당 입력 값 두 개의 부모를 찾아 union 시켜주면 됩니다.
1일 때, 두 개의 부모가 같은지 다른지를 판별하면 됩니다.
> 1647번
최소 스패닝 트리를 구한다음, 맨 마지막에 오는 간선의 길이를 빼면 최소의 유지비로 마을 두개를 분리할 수 있습니다.
> [week3] 김민수

- src/heejin/week2/Week2_1149.java
- src/heejin/week2/Week2_12865.java
- src/heejin/week2/Week2_2156.java
- src/heejin/week2/Week2_2668.java
- src/heejin/week3/Week3_1647.java
- src/heejin/week3/Week3_1717.java
- src/heejin/week3/Week3_24542.java
> 김희진
> 1647 도시 분할 계획
- 자기 자신을 부모로 초기화 = 마을 개수 N개로 초기화
- 최소 유지비 합을 위해 유지비를 기준으로 오름차순으로 정렬
- 마을이 2개가 될 때까지 유니온
- 서로 다른 마을에 속하면(최상위 부모가 다르면) 합치기
> 1717 집합의 표현
- 자기 자신을 부모로 초기화 
- 명령어에 따라 합집합 or 같은 집합 포함 확인 연산 수행
- 합집합: 작은 값 쪽으로 집합 합치기
- 같은 집합 포함 확인: 최상위 부모가 같으면 같은 집합
> 24542 튜터-튜티 관계의 수
- 자기 자신을 부모로 초기화 
- 같은 집합이 아니면서 합칠 수 있으면 유니온 
- 각 집합에 속하는 교육생 수 곱하기
- 같은 집합 내에서 튜터를 한 명만 선정하면 됨
- 1번 집합에서 튜터를 선정하는 경우의 수 * 2번 집합에서 튜터를 선정하는 경우의 수 * ...
> [week3] 김희진

- src/jiyeon/week3/boj_1647.java
- src/jiyeon/week3/boj_1717.java
- src/jiyeon/week3/boj_2225.java
- src/jiyeon/week3/boj_24542.java
> 황지연 
> **2225. 합분해** 
>
> dp [i][j] 배열을 "정수 i를 j개 이용해서 만드는 경우의 수" 라고 정의를 하고 점화식을 세워보려고 노력하였다.
> 
> **dp[i][j]** = dp[1][j-1] + dp[2][j-1] + dp[3][j-1] + ... + **dp[i-1][j-1]**+**dp[i][j-1]**
>
> 이 점화식에 빗대어보아 생각해보면 
> **dp[i-1][j]** = dp[1][j-1] + dp[2][j-1] + dp[3][j-1]  + ... + **dp[i-1][j-1]**
> 임을 알 수 있다. 
> 
> 따라서 점화식은
> dp[i][j] = dp[i-1][j] +dp[i][j-1] 임을 알 수 있고, 해당 점화식을 이용하여 문제를 풀이하였다. 
<br></br>
>  **24542. 튜터-튜티 관계의 수**
>
> 해당 문제의 조건을 잘 살펴보면 결국 정답은 **각 그래프의 정점(노드)의 개수를 곱한 것**과 같다. 
>
> 따라서, 이 문제는 유니온 파인드 뿐만 아니라 dfs,bfs로도 간단하게 풀 수 있지만 나는 유니온 파인드를 이용하여 풀이하였다.
>
>유니온파인드 알고리즘을 이용하여 모든 간선을 이어주면, arr 배열의 요소는 각 그래프의 루트 부모를 가지게 된다. 
>
> 이를 Hash Map을 이용하여 카운트 해주었고, (key : 루트 부모, value : 카운트한 수) 마지막에 모든 value를 곱해주었다.
<br></br>
> **1717. 집합의 표현** 
> 기본적인 유니온파인드 문제이다. 풀이 방법은 24542번 문제와 …
> [week3] 황지연

- src/jinu/week3/Week3_1647.java
- src/jinu/week3/Week3_1717.java
- src/jinu/week3/Week3_24542.java
> ex) 이진우
- parent 배열을 사용하고 배열 초기화 
- parent 배열의 원소값이 작은 것을 부모값으로 갱신하는 식으로 집합 형성
- 각자의 집합에 대한 노드 수 의 곱이 정답이라고 생각
- 각자의 집합을 이루기 위해서 Union find 사용 
- long 값으로 선언을 안했기에 다수 틀림. 
- kruskal 알고리즘을 활용하고, 최소 비용 신장 트리를 형성
- 트리를 이루는 간선의 합에서 가중치가 가장 큰 값을 빼줌. 
>
> [week3] 이진우

- src/youngtae/week4/Week4_15565.java
- src/youngtae/week4/Week4_16562.java
- src/youngtae/week4/Week4_22945.java
- src/youngtae/week4/Week4_7795.java
> 권영태
> 7795(먹을 것인가 먹힐 것인가)
>> A 집단에서 A가 B 집단보다 큰 쌍의 개수를 얻어야 함. B 집단의 기존 순서는 중요하지 않고 A의 값`k` 보다 작은 B의 개수(`B(i)<k`)를 구하면 되기 때문에, B집단을 정렬한다.
이후 반복문을 통해 `k`를 구하고, `arrB[0](==st), arrB[M-1](==ed)` 두 개의 포인터 각각 이동시켜  **`k`보다 작은 수 중 가장 큰 수의 위치**를 찾으면 된다.
> 15565(귀여운 라이언)
>> K개 이상 라이언이 연속된 집합 중 가작 작은 집합의 크기를 구하는 문제.  먼저, `1<=K<=10^6`라는 조건이 있기에 K==1일 때 조건을 추가해주면 보다 빠르게 처리할 수 있다. `arr[i](==st), arr[i+1](==ed)`를 선언하고 ed를 한칸 씩 이동시키면서 각 라이언의 위치와 K개 이상 연속된 라이언의 집합을 찾는다. 각 라이언의 위치는 `queue`에 저장해두고, K 개 이상 연속된 집합이라면 최소 집합인지 확인하고 st를 해당 구간 중 앞에 있는 라이언의 위치(index != st, index > st)으로 변경한다. 이런 반복을 통해서 가장 작은 연속된 집합 크기를 구한다.
> 22945(팀 빌딩)
>> 정렬되어 있지 않은 개발자 집단에서 A와 B사이 존재하는 다른 개발자 수를 최대로 늘린다고 최대값이 될 수가 없음.(A, B의 능력치가 1이라면 최대 보장X)
그렇기에 min(A,B)을 최대로 올려야함. `arr[0](==st), arr[N-1](==ed)` 두 포인터를 만들고 `arr[st] > …
> [week4] 권영태

- src/jiyeon/week4/boj_15565.java
- src/jiyeon/week4/boj_16562.java
- src/jiyeon/week4/boj_22945.java
- src/jiyeon/week4/boj_7795.java
> 황지연
> **7795번 - 먹을 것인가 먹힐 것인가**
>
> 문제만 본다면 A>B 일 때 카운트를 하면 되는 간단한 문제이다. 하지만 주어진 입력 그대로 로직을 진행한다면 시간 초과가 난다. 
> 시간 복잡도를 줄이기 위해 사용한 방법은 정렬이다. A와 B를 오름차순으로 정렬한 다음, A<=B가 발생하는 순간 break를 걸어 반복을 종료 시키고 다음 A의 값으로 넘어가도록 하였다. 
>
>
>**15565번 - 귀여운 라이언** 
>
> 나에게 정말 어려웠던 문제이다,,,
> 이 문제에서 핵심은 반복을 한 번만 해야한다는 것이라고 생각한다. 이를 위해 라이언인형의 인덱스를 저장하는 큐를 만든 후, 탐색을 하면서 찾은 모든 라이언 인덱스를 저장해주었다. 
> 중요한 점은 count가 K를 만족했을 때, start 포인터를 queue.poll() 의 결과로 이동해 주는 것과 이 경우 라이언 인형이 하나 없어지는 것이기 때문에 카운트를 하나 빼주는 것이다. 이 PS idea를 생각를 못해서 많이 틀렸다. 
>
>
>**22945번 - 팀 빌딩**
>
>전형적인 two pointer 문제라고 생각한다. 골드 4지만 라이언문제보다 쉽다.!
> 개발자 배열의 처음부터 시작하는 start 포인터와, 마지막에서부터 역순으로 이동하는 end 포인터를 지정해주고, start와 end 인덱스에 해당하는 값을 기준으로 능력치를 계산해주었다.
> ""최댓값""을 찾는 문제이기 때문에,  dev[start]와 dev[end] 중 값이 작은 것에 해당하는 포인터를 이동시켜주었다.
> 그리고 start>end가 되는 순간, …
> [week4] 황지연

- src/heejin/week4/Week4_15565.java
- src/heejin/week4/Week4_22945.java
- src/heejin/week4/Week4_7795.java
> 김희진
> 7795 먹을 것인가 먹힐 것인가
B를 정렬해준 다음, 이분 탐색을 이용하여 B 배열에서 A[i]보다 커지는 시점을 찾습니다. 
인덱스가 0부터 시작이므로 A[i]가 처음 잡아 먹을 수 없는 시점의 인덱스가 잡아 먹을 수 있는 개수를 의미합니다.
> 15565 귀여운 라이언
입력 받을 때 라이언 위치(인덱스)를 리스트에 저장합니다.
만약 라이언의 개수가 K보다 작으면 K개 이상의 라이언을 초함한 집합이 존재할 수 없으므로 -1을 출력하고 종료합니다.
그렇지 않으면 두 포인터의 차이가 K-1이 되도록 고정하여 라이언을 저장한 리스트를 순회합니다.
(번외)
처음에는 답을 계산할 때 투 포인터가 아닌 아래처럼 구현해서 맞았습니다..
```java
for(int i=0; i + K - 1 <lion.size(); i++){
answer = Math.min(answer, lion.get(i+K-1) - lion.get(i) + 1);
}
```
근데 주제가 투 포인터이다 보니 해당 방식으로 수정해서 다시 제출했습니다ㅎㅎ
> 22945 팀 빌딩
시작 포인터는 0, 끝 포인터는 N-1로 초기화합니다.
두 포인터가 가리키는 개발자 두 명 팀의 능력치를 계산하여 능력치 최댓값 변수를 업데이트 해줍니다.
`min(개발자 A의 능력치, 개발자 B의 능력치)`가 최대가 되려면 두 포인터 중 더 큰 능력치를 가진 개발자를 남겨야 합니다.
따라서 더 작은 능력치를 가진 개발자 포인터 값만 업데이트 해줍니다.
> [week4] 김희진

- src/kijung/week4/Week4_15565.java
- src/kijung/week4/Week4_22945.java
- src/kijung/week4/Week4_7795.java
> 박기정
> 귀여운 라이언(15565)
- 포인터를 같은 시작점에 위치
- 라이언을 K개 찾을 때까지 right 포인터 증가
- K개라면 K개가 유지될 때까지 answer 갱신 및 left 포인터 증가
> 먹을 것인가 먹힐 것인가(7795)
- 크기 순으로 정렬
- 이분 탐색으로 target 보다 작은 것의 개수 찾기
> 팀 빌딩(22945)
- 포인터를 양 옆에 위치
- 전력을 갱신하며 양 옆 중 더 작은 값의 포인터를 증가/감소
- 양 옆 값 중 작은 값은 더 큰 전력값 갱신에 필요없기에 제외시킴
> 7795번 문제에서 이분탐색만 바로 떠올랐는데 다른 분들은 어떠신가요?
> [week4] 박기정

- src/minsu/week5/강의실배정.java
- src/minsu/week5/비트문자열재배열하기.java
- src/minsu/week5/카드합체놀이.java
> 김민수
> 10330번 비트 문자열 재배열하기
예제 입력 3번째 줄에 주어지는 값으로 만들 수 있는 숫자를 먼저 만듭니다.
ex) 1 3 2
100011, 011100 이런식으로 수를 만들고,
예제 두 번째 줄에 주어지는 0과 1 갯수로 만들 수 있는지 먼저 확인을 하고,
만들 수 있을 때, 각 1과 0을 스왑하는 형태로 구현하였습니다.
각 1과 0은 가장 가까우면서 다른 숫자를 스왑하며 그 거리만큼 연산 수를 더해줍니다.
> 11000번 강의실 배정
먼저 강의실 시작시간과 끝나는 시간이 입력 값으로 주어졌는데,
시작 시간 기준으로 정렬을 하였습니다.
힙 배열 구조에 맨 앞 시작하는 강의를 넣고 필요한 강의장 갯수를 구하였습니다.
이전 강의 끝나는 시간과 비교할 강의장 시작 시간을 비교하여,
강의장 시작 시간이 전 강의 끝나는 시간보다 전이라면 힙 배열에 넣어주고
강의장 시작 시간이 전 강의 끝나는 시간보다 그 이후라면 전 강의를 힙 구조에 빼주고
다음 강의를 힙 구조에 넣어줍니다.
마지막으로 강의장 갯수는 힙에 들어간 강의장 총 갯수를 나타냅니다.
>15903 카드 합체 놀이
입력 값으로 주어진 카드들을 우선순위 큐에 넣어서 카드 두 개를 poll() 해줍니다.
그리고 두 개 카드를 더한 값을 두 번 우선 순위 큐에 넣어줍니다. 이 동작을 반복합니다.
>
> [week5] 김민수

- src/jinu/week6/Baekjoon_11559.java
- src/jinu/week6/Baekjoon_17142.java
- src/jinu/week6/Baekjoon_9519.java
> 이진우
- Char 배열에 현재 상태 초기화 
- 색깔이 있는 경우 DFS 를 사용하여 인접한 색깔이 4개 이상인지 판단 
-  4개 이상이라면 폭발 여부를 나타내는 ```'.'``` 으로 초기화 
- 폭발 이후에 Queue 에 다가 색깔이 있는 것을 담고 아래로 drop 
- 문자열을 주어진 규칙에 맞게 돌려 같은 문자열이 나오는 주기를 구함
- 돌려야할 숫자를 주기로 나누어 나오는 나머지 값을 이용하여 실질적으로 몇 번 돌려야 하는지 선택
- 그 숫자만큼 돌리기
- 백트래킹을 사용하여 비활성화된 바이러스 중 m 개의 활성화 바이러스 선택
- 활성화 바이러스 기반으로 BFS 를 사용하여 모든 빈칸에 전파되기 까지 얼마나 걸리는지 시간을 관리하여 구함. 
- BFS 과정 중 빈 칸이라면 최대 시간 갱신, 그렇지 않다면 최대 시간을 갱신하지 않는다. 
>
> [week6] 이진우

- src/jiyeon/week6/boj_11559.java
- src/jiyeon/week6/boj_17142.java
- src/jiyeon/week6/boj_9519.java
> 황지연
> **11559 뿌요뿌요**
> 
> 저의 로직은 다음과 같습니다.
>1. 턴마다 전체 뿌요 맵을 순회 
>
>2.  '.'을 만나면 건너뛰고, 방문하지 않은 뿌요를 만나면 같은 색의 뿌요인 경우에만 BFS 진행하며 뿌요 좌표를 큐에 넣음 
>
>3. 한 번의 뿌요 탐색을 끝낸 후 이어져 있는 뿌요가 4개 이상이라면
> -> 뿌요 터뜨리기 &&  떨어져야하는 뿌요 좌표를 저장하는 큐에 담기 / 4개 미만 -> queue clear 
>
> 4. 전체 뿌요 맵 순회가 끝나면 ( 한 턴이 끝나면) 뿌요를 내려줍니다. 이 때, 뿌요를 정확하게 내리기 위하여 **PQ에 담아 위쪽에 위치한  뿌요부터 내려줬습니다.** (이렇게 하지 않으면 뿌요가 이상하게 내려감) 
>5. 만약 내려줘야 하는 뿌요가 없다면 -> 더 이상 맵을 순회하지 않고 결과를 출력합니다.
>
>
>**9519 졸려** 
>
> 좀 이상하게 풀었습니다 ㅎㅎ StringBuilder 사용하는 정석 풀이는 아니니 이렇게 푸는 방법도 있구나 참고만 해주세요
> 
> 1. 먼저 입력 단어를 LinkedList에 한 글자씩 넣어줍니다. 
>
> 2. setFoward() 메서드를 이용하여 단어를 문제에서 주어진 대로 섞는 것이 아니라, **한 턴 전의 단어 셔플로 롤백 합니다.**
>
> 3. 이 방법을 이용하여 계속 롤백을 하면서 주기를 찾고, N번 롤백할 때마다의 결과를 저장합니다.
>
>4. ( X % 주기 - 1 ) 번 째 결과가 곧 정답 
>
>**17142  연구소3**
>
>
> 1. 먼저 입력을 받으며 바이러스의 좌표를 …
> [week6] 황지연

- src/youngtae/week6/Week6_11559.java
- src/youngtae/week6/Week6_13164.java
- src/youngtae/week6/Week6_17142.java
- src/youngtae/week6/Week6_9519.java
> 권영태
> 9519(졸려)
>> 처음에 주기를 찾아야 할까 싶다가 완전탐색으로 풀어도 괜찮지 않을까 싶었는데 시간 초과 발생.. 이후 `HashMap` 또는 `String`들이 문제인가 싶어서 고쳐봤지만 시간초과가 여전히 발생했고, 주기를 찾는 방식으로 변경해도 메모리 초과 발생^_^
하루 종일 시도하다가 결국 구글링을 통해 답안 해결... 추후 다시 풀어보고 연습해야겠음
> 11559(Puyo Puyo)
>> BFS 탐색을 통해 4개 이상 이어진 뿌요 집단들을 찾아 터뜨린뒤 가장 아래에서부터 뿌요가 터진 곳부터 down() 시키면 될 것 같다고 생각했음.
중간에 터진 뿌요 위치를 저장하는게 조금 힘들었는데 `List<Node>`를 이용해서 잘 해결했던 것 같음. `<- 더 좋은 방식이 있으면 조언 부탁드립니닷`
> 13164(행복 유치원)
>> 인접한 원생의 키 차이를 오름차순으로 저장한 뒤 N-K개만큼 차례대로 꺼내서 더하면 된다.
> 17142(연구소 3)
>> 모든 바이러스의 위치를 저장하고 M개의 바이러스를 선택하는 조합 리스트를 만든 뒤 각 조합의 결과(최소 일수)를 찾으면 된다고 생각했음.
처음에 조합 리스트를 뽑을 때 2중 반목문을 이용해서 뽑았는데 예상과 다르게 만들어졌었음. 그리고 생각해보니 이 방식은 시간이 엄청 걸려 시간초과가 나지 않을까 생각했고 백 트래킹을 통해 조합을 뽑을 수 있다는 생각을 떠올라 해당 방식으로 구현함.
>
> 11559(Puyo Puyo) 
>> 중간에 터진 뿌요 위치를 저장하는게 조금 힘들었는데 …
> [week6] 권영태

- src/heejin/week7/Week7_17940.java
- src/heejin/week7/Week7_20160.java
- src/heejin/week7/Week7_31938.java
> 김희진
> 20160 야쿠르트 아줌마 야쿠르트 주세요
- 나의 출발점으로부터 모든 정점까지의 최단거리 구하기
- 야쿠르트 아줌마의 정점을 하나씩 옮기면서 ans 업데이트
-  야쿠르트 아줌마의 현재 정점으로부터 모든 정점까지의 최단 거리 구하기
- 갈 수 없는 정점들은 패스하고 다음 정점으로 이동
- 내가 야쿠르트 아줌마보다 같거나 일찍 도착하면 야쿠르트 살 수 있음 -> ans 업데이트
> 17940 지하철
- 시작점 0부터 모든 정점까지의 적게 환승하면서 최소 시간으로 가는 경로 구하기
- 각 정점의 환승 횟수는 transfer 배열에, 걸리는 시간은 dist 배열에 저장
- 현재 정점에서 다음 정점으로 갈 때, 기존 환승 횟수보다 환승이 더 적으면 값 업데이트
- 마찬가지로 환승 횟수는 동일하지만 이동 시간이 더 짧으면 값 업데이트
> 31938 현대모비스 트럭 군집수행
- 시작점 1로부터 다른 정점까지의 최단 거리 구하기
- 현재 정점에서 다음 정점으로 갈 때, 거리가 더 짧으면 부모 노드 업데이트 후 pq에 추가
- 마찬가지로 거리는 같은데 새로운 부모의 거리가 더 오래걸리면 부모 업데이트
- 트럭 개수가 많은 부모까지의 거리가 더 오래 걸려야, 트럭 개수가 감소된 다음 노드로 갈 때 cost가 낮음
- 각 트럭은 부모 노드까지는 0.9 비용으로 오고, 자신의 번호 노드로 가는 길은 100% 비용이 듦
> [week7] 김희진

- src/minsu/week7/야구르트_20160.java
- src/minsu/week7/오목_2072.java
- src/minsu/week7/지하철_17940.java
- src/minsu/week7/현대모비스_31938.java
> 김민수
> 오목(2072)
모든 수를 다 놓고 나서 오목이 될 것을 찾고
오목이 된 것중에서 가장 큰 값을 찾고
큰 값들 중에 가장 작은 값을 구합니다.
> 야구르트
야구르트 아주머니가 1번 장소부터 10번 장소들 중 갈 수 있는 장소들로 차례대로 방문했을 때
걸리는 시간을 구하고
내가 출발지로부터 갈 수 있는 노드에 걸리는 시간을 구해서 비교하여 가장 작은 노드의 번호를 구합니다.
> 지하철
우선순위 큐의 조건을 1. 환승 횟수, 2.환승 횟수가 같다면 최저 시간으로 잡습니다.
> 현대 모비스
우선순위 큐의 조건은 짧으면서 각 노드들이 연결된 노드들 간의 가중치가 제일 짧은걸 골라야합니다.
트리를 형성하면 각 노드별 각 정점을 포함한 서브트리 노드 갯수를 구하고
각 정점에서 구한 갯수들이 트럭을 보내야 할 숫자입니다.
>
> [week7] 김민수

- src/jinu/week8/Week8_1477.java
- src/jinu/week8/Week8_17951.java
- src/jinu/week8/Week8_32718.java
> 이진우
- left, right , mid 의 의미: 휴게소가 없는 구간의 최댓값으로 선정 
- 휴게소가 없는 구간의 최댓값으로 최대한 지을 수 있는 휴게소 갯수 계산 
- 위 값이 주어진 M값 보다 크면 휴게소가 없는 구간의 최댓값을 올려 휴게소 갯수를 낮춘다. 
- 그렇지 않으면 휴게소가 없는 구간의 최댓값을 낮추어 휴게소 갯수를 올린다. 
- 값이 같을 때도 휴게소가 없는 구간의 최댓값을 최대한 줄여 최댓값의 최솟값을 구하도록 한다. 
- left,right,mid 의 의미: 현수가 받을 수 있는 최소 점수 
- 이 점수를 기준으로 최대 몇개의 그룹이 형성되는지 판단.
- 그룹의 개수가 지정된 갯수 K 보다 클 떄 그룹의 개수를 줄이기 위해서 시험 점수 최솟값을 늘린다. 
- 그롭의 개수가 지정된 갯수 K보다 작을 때 그룹의 개수를 늘리기 위해서 시험 점수 최솟값을 줄인다. 
- 그룹의 개수가 지정된 갯수 K와 같을 때도 그룹 최솟값을 맞추기 위해 시험 점수 최솟값을 줄인다.
- 일련의 과정 이후의 최댓값을 구하고 싶다면 원본 배열에서 그 최댓값의 결과를 나타내는 값을 미리 계산하여 그 결과와 가장 가까운 것을 찾는다. 
- 정답 코드 참조.. 
>
> [week8] 이진우

- src/jiyeon/week8/boj_1477.java
- src/jiyeon/week8/boj_17951.java
- src/jiyeon/week8/boj_32718.java
> 황지연
**> 1477번 휴게소 세우기** 
매개변수 탐색 문제를 풀 때는 left, right, 그리고 조건을 판단하는 기준만 잘 세우면 빠르게 풀 수 있다.
하지만 그걸 잘 세우는게 어렵긴하다. 
휴게소 세우기 문제 같은 경우에는 
- **left (조건을 항상 만족하는 경우)** : 1 (사실 원론적으로는 0이 맞는데 divide by zero error가 나서 1로 변경해주었다.)
- **right (무조건 조건이 만족하지 않는 경우)** : L (==고속도로의 총 길이)
- 조건 : 최대 구간이 mid일 경우 몇 개의 휴게소를 더 지어야 하는가? 
이렇게 각 변수를 정의하여 문제를 풀었다. 나머지 탐색 구현은 일반적인 매개변수(이분)탐색과 동일하다.
----
**> 17951번 흩날리는 시험지 속에서 내 평점이 느껴진거야**
위 문제도 매개 변수 탐색 문제이다. 
이 문제는 매개변수 탐색의 특징인  _최대 값 중에 최소 값 반환 이라는 특징_ 을 정확하게 몰라서 많이 틀렸다. 
마찬가지로 매개변수 탐색에서는 left, right 변수가 가지는 의미가 더욱 중요해지기 때문에 
- **left : 0점인 경우**
- **right : 주어진 시험지 점수의 총 합** 으로 정의하여 문제를 풀었다. 
----
**> 32718번 우선순위 큐와 시뮬레이션** 
이건 내 기준 현대 모비스 문제보다 더 어려웠다. 
왜냐면 뭘 알아야 접근을 할텐데 . . . 아무것도 몰라서 너무 어려웠다. 
이 문제는 입력 범위가 크기 때문에 O(N) 미만의 시간복잡도로 풀어야한다. 
하지만 주어진 요구 사항을 착실히 …
> [week8] 황지연

- src/minsu/week8/Week8_1477.java
- src/minsu/week8/Week8_17951.java
- src/minsu/week8/Week8_32718.java
> 김민수
> 휴게소 세우기 1477번
주어진 휴게소 간의 거리를 구합니다.
휴게소 간의 거리에 몇 m간격으로 휴게소를 지을 수 있는지 이진 탐색을 활용하여 구합니다.
휴게소가 없는 구간의 길이의 최대값읓 최소로 하는 조건을 찾습니다.
> 우선순위 큐와 시뮬레이션 32718
모듈러 연산을 어떻게 나누어서 실행속도를 줄일것긴가의 문제인 것 같습니다..
> 흩날리는 시험지 속에서 내 평점이 느껴진거야 17951
주어진 맞은 점수의 총점을 구해서 범위를 0부터 총점 +1을 하여 이진 탐색을 실시하였습니다.
mid가 구해지면 isPoss 메서드를 활용하여 구간 K개 이상 나오는지 확인하고
그 중 가장 큰 점수를 찾습니다
>
> [week8] 김민수

- src/minsu/week9/Week9_1052.java
- src/minsu/week9/Week9_10728.java
- src/minsu/week9/Week9_15661.java
> 김민수
> 물병 1052
N에 1씩 추가하면서 비트 1의 갯수가 K개 이하가 됬을 때 종료시키게 로직을 구성하였습니다.
> 링크와 스타트 15661
dfs 방식과 수학적 방법과, dfs와 비트연산으로 방문처리하는 것으로 구하였습니다.
> xor 삼형제1
코드에 리뷰 달았음요
>
> [week9] 김민수

- src/kijung/week9/Week9_1052.java
- src/kijung/week9/Week9_10728.java
- src/kijung/week9/Week9_15661.java
> 박기정
> 1052번 물병
- Integer.bitCount(N)을 이용해 현재 물병 개수를 비트 1의 개수로 확인
- 물병 개수가 K 이하면 종료, 초과하면 추가해야 할 최소 개수를 계산
- N += idx로 가장 낮은 1의 위치를 채우며 물병 개수를 줄여 나감
> 15661번 링크와 스타트
- 1 << N을 이용해 모든 팀 구성 경우의 수를 탐색
- 특정 비트가 0이면 팀 A, 1이면 팀 B에 배정하여 조합을 생성
- 두 팀의 점수 차이를 비교하여 최솟값을 갱신
> 10728번 XOR 삼형제 1
- 1 << size를 사용해 모든 부분집합을 확인하고 포함된 원소를 candidates 리스트에 추가
- 특정 부분집합이 XOR 연산 조건을 만족하는지 check() 함수를 통해 검증
- 유효한 부분집합 중 가장 큰 크기를 유지하면서 최적의 해를 찾기
> 비마 너무 어려워요오
> [week9] 박기정

- src/jiyeon/week10/boj_1036.java
- src/jiyeon/week10/boj_10859.java
- src/jiyeon/week10/boj_3192.java
> 황지연
> 3192번 매직스퀘어
3X3 매직스퀘어는 아래와 같은 특징들을 가지고 있다.
- 센터 칸 (1,1)을 기준으로 대칭된 위치에 있는 합들이 같다. 이를 나는 **대칭합**이라고 명칭하겠다.
- 예를 들자면` (0,0)과 (2,2)의 합`과 `(2,0)과 (0,2)의 합`이 같다. 
- 센터 칸(1,1)의 값은 항상 `대칭 합/2 `의 값을 가지고 있다.
- 그리고 한 열/한 행/ 한 대각선의 합은 항상 `센터 칸*3`의 값이다.
문제에  "숫자를 많아야 세 개만 지웠다."라는 조건이 있기 떄문에 우리는 입력에 상관없이 _항상 대칭합을 구할 수 있다._ 
그러면 자연스럽게 앞서 설명한 센터 칸의 값, 한 행의 합들을 구할 수 있다.
이 후 로직은 간단하다.
- 입력을 받으면서 빈칸의 좌표를 큐에 저장한다
- 그 후 3X3 배열을 돌며 대칭 합을 구한다. 
- `queue.poll()` 을 하며 (대칭합 OR 센터 칸의 값 OR 한 행/열/대각선의 합)을 이용하여 빈칸의 값을 구한다. 
----
> 1036번 36진수
이 문제의 가장 핵심은 "어떤 알파벳(혹은 숫자)를 'Z'로 바꿔야 합이 최대가 될까?"이다. 
그러기 위해서는 가장 작은 가치를 가진 진수를 'Z'로 바꾸는 그리디적인 접근이 필요하다.
(무턱대고 값이 작은 진수를 Z로 바꾸면 안된다)
각 진수가 가진 가치를 구하기 위해서 아래와 같은 로직을 이용하였다.
- 먼저 주어진 String을 역순 인덱스로 쪼개서 자릿수 별로 쪼개서 ArrayList에 저장한다.
- 그 후 ArrayList를 돌며 각 알파벳이 가진 가치를 36진수 -> …
> [week10] 황지연

- src/heejin/week10/Week10_1036.java
- src/heejin/week10/Week10_10859.java
- src/heejin/week10/Week10_3192.java
> 김희진
> 10859 뒤집어진 소수
- 먼저 N이 소수인지 판별한다
- 1은 소수가 아니다
- 2는 소수이다
- 2로 나누어지는 짝수는 소수가 아니다
- 그 외의 홀수라면 루트 num까지 검사하여 나누어 떨어지는지 확인한다
- N의 뒷자리부터 거꾸로 뒤집는다.
- 3,4,7이면 더 이상 숫자가 아니므로 no를 출력하고 끝낸다.
- 뒤집은 N이 동일하게 소수인지 판별해서 no 또는 yes를 출력한다.
> 3192 매직 스퀘어
- 0이 없는 가로, 세로, 대각선이 없는 경우를 대비하여 입력받을 때 모든 값을 더해준다.
- 0이 3개일 때는, 이 합을 2로 나눈 것이 한 줄의 합과 동일하다.
- 기본적으로 모든 줄(가로, 세로, 대각선)의 합은 동일하다.
- 0이 3개이면, 현재 2줄밖에 없는 것으로 이를 2로 나누면 한줄의 합과 동일한 것이다.
- 0이 3개가 아닌 경우를 위해 0이 없는 줄을 찾아 한 줄의 합을 구한다.
- 합을 구하면 지워진 0의 값을 계산해 채운다.
- 0이 하나인 줄에서 (한 줄의 합) - (나머지 숫자 합) 이 0칸의 원래 값이 된다.
> 1036 36진수
- 문자열을 입력받을 때마다 각 숫자의 가치를 계산한다.
- 36진수를 0~36 사이의 숫자로 변환해준다.
- 자리수에 따라 36의 제곱수의 가중치를 가진다. ex) 10의 자리 수 = 36^1의 가중치
- Z와의 크기 차이(35 - 숫자)와 가중치를 곱하여 최종 가치를 구한다.
- 각 숫자별 가치를 저장하는 gain에 앞서 구한 최종 가치를 더해준다.
- gain이 0보다 큰 숫자들은 pq를 이용해 가치 기준 내림차순으로 …
> [week10] 김희진

- src/yeoeun/week10/Week10_1036.java
- src/yeoeun/week10/Week10_10859.java
- src/yeoeun/week10/Week10_3192.java
> 양여은
> 1036 : 36진수
- 자리값(int)과 문자(char)를 서로 변환해주는 메소드를 사용하였습니다.
- 입력받은 문자열에 대해 각 문자의 score값을 더해주고, 그 최종 값을 sort함으로써 Z로 변환시켰을 때 가장 값이 커지는 문자 K개를 선정하였습니다.
- 두 문자열을 받아서 맨 끝자리부터 차례대로 더하고, 36 이상이면 upper로 올림값을 전달하는 덧셈 방식을 사용하였습니다.
> 3192 : 매직 스퀘어
- sum값을 구하기 위해 항상 가운데 수를 먼저 구하는 방식을 사용하였습니다.
- 가운데를 포함하는 직선을 만드는 경우의 수는 4가지이지만, 빈칸은 최대 3개이기 때문에 반드시 중앙값을 구할 수 있게 됩니다. 이후 이 값을 통해 기준이 되는 sum값을 구했습니다.
- 이후, 빈칸들에 대해 가로→세로→대각선 순으로 검사하며 빈칸을 채울 수 있는 경우가 있다면 값을 채우고 다음 빈칸으로 넘어갑니다. 만약 불가능하다면 다른 빈칸을 먼저 검사합니다.
> 10859 : 뒤집어진 소수
- 어떤 수의 약수의 중간값은 sqrt값이기 때문에 해당 값까지만 검사를 진행하였습니다.
- 만약 입력된 값이 소수가 아니라면 no를 출력하고 프로그램을 정지합니다.
- 소수인 경우, 뒤집기를 진행합니다. 각 케이스마다 새로운 값을 계산해주었습니다.
- 계산된 결과가 소수인지 확인합니다.
코드 깔끔하게 만드는게 너무 어렵네요..ㅠㅠ
> [week10] 양여은

- src/jinu/week10/Week10_1036.java
- src/jinu/week10/Week10_10859.java
- src/jinu/week10/Week10_3192.java
> ex) 이진우
1. (3,4,7) 을 포함하는지 여부를 검사하여 포함한다면 NO출력 
2. 기존 String 을 거꾸로 뒤집는 과정에서 6은 9로 9는 6으로 전환 
3. 각각 소수 판별 알고리즘 적용 (Math.sqrt 이용) 
- 먼저 3개의 총 합을 구하려고 시도. 
- 0 이 존재하지 않는 행또는 열이 있다면 바로 세 합을 구할 수 있기에 빈 칸의 열과 행을 추출해서 나타나지 않은 행과 열이 있는지 검사 
- 0이  존재하지 않는 행또는 열이 없다면 대각선을 확인합니다.
- 대각선 또한 존재하지 않는다면 대각선의 형태로 값이 3개가 연속하는 경우입니다. 이 경우 총 합에서 나누기 / 2를 해주면 됩니다 
(대각선의 원소를 x,y,z 으로 두고 방정식을 세워 증명 가능 ) 
- 이후 3개의 합을 바탕으로 원소를 채우고 출력 
- 가치의 총합 은 long 형을 초과하므로 BigInteger 사용 
- Map을 선언하여 이 가치를 관리 (key: 기존값을 int 형 36 진수로 바꾼값 (0 - 35) , value 에는 Z로 바꾸었을 때의 가치 ) 
- value 기준으로 정렬한 이후 상위 K 개에 Z를 넣는 다는 의미로 arr 에 35 삽입 
- 이후 모든 문자열을 순회하며 값을 더한다(num에 삽입) (num은 자릿수에 따른 값을 의미 ) 
- num 의 값을 36진수로 전환 
틀린 부분 다시 공부해서 오겠슴다..
> [week10] 이진우

- src/kijung/week10/Week10_1036.java
- src/kijung/week10/Week10_10859.java
- src/kijung/week10/Week10_3192.java
> 박기정
> 1036
- 각 숫자(0~Z)를 Z로 바꿨을 때 얻을 수 있는 이득을 계산하여 gain[] 배열에 저장
- gain[] 배열을 기준으로 이득이 큰 문자 K개를 정렬 후 선택하여, 해당 문자를 전부 Z로 치환하여 최종 합을 최대화
- BigInteger 사용
> 10859
- 6↔9를 변환하고 나머지 숫자는 그대로 뒤집는 방식으로 새로운 숫자를 생성
- 3,4,7은 뒤집을 수 없기 때문에 실패 처리
- 뒤집은 결과의 첫 자리가 0인 경우, 유효한 숫자가 아니므로 즉시 “no”를 출력
- isPrime 함수를 통해 입력값과 뒤집힌 숫자 모두 소수인지 확인하고, 둘 다 소수일 때만 “yes”를 출력
> 3192
- 0의 개수가 적은 줄부터 차례대로 처리하기 위해 PriorityQueue를 활용
- 이미 완성된 줄이 있다면 해당 줄의 합을 기준 합으로 설정, 없다면 전체 합의 절반을 기준으로 설정하여 균형
- 1개의 0은 단순히 보정값을 넣고, 2개의 0은 나머지 값과 기준 합을 통해 역으로 계산하여 채우는 로직을 구
> 3192는 카카시 좀 했습니다 헤헤...
> [week10] 박기정

- src/minsu/week11/Week11_11657.java
- src/minsu/week11/Week11_258709.java
- src/minsu/week11/Week11_258711.java
> 김민수
> 타임 머신은 벨만포드의 정형화된 코드로 문제를 풀었습니다.
> 주사위 문제는 조합과 이분탐색을 활용하여 문제를 풀었습니다.
> 도넛과 막대 그래프 문제는 트리의 특성을 가지고 문제를 접근하였습니다.
> [week11] 김민수

- src/jiyeon/week11/boj_11657.java
- src/jiyeon/week11/도넛과 막대 그래프.java
- src/jiyeon/week11/주사위 고르기.java
> 황지연 
> 백준 11657번 타임 머신 
시간 C (가중치)가 음수인 경우가 있기 때문에 벨만-포드 알고리즘을 이용해 풀이하면 된다. 
벨만-포드 알고리즘 정석 문제 
주의 할 점은 음수 사이클이 있는지 여부를 구해야한다. 만약 음수 사이클이 발생할 경우, 해당 경로는 음의 무한대로 빠지므로 -1을 리턴해야한다. 
> 프로그래머스  도넛과 막대그래프 (lv.2)
그래프를 그려서 탐색해야하는 줄 알았지만, 각 그래프 (도넛, 8자, 막대)의 정점의 특징을 찾아 개수를 구하면 된다.
생성된 정점은 나가는 간선의 개수가 2개 이상, 들어오는 간선의 개수는 0개이다. 
8자 그래프는 나가는 간선의 개수가 2개, 들어오는 간선의 개수는 2개 이상이다.
(정확하게는 들어오는 간선의 개수도 2개여야하지만, 생성된 정점과 이어질 수도 있기 때문에 2개 이상으로 판단해야한다.)
막대 그래프는 나가는 간선의 개수는 0개, 들어오는 간선의 개수는 1개 이상이다. 
도넛 그래프는 생성된 정점에서 나가는 간선의 개수( == 전체 그래프 개수)에다가 8자, 막대 그래프의 개수를 빼주면 된다. 
각 정점의 나가는 간선과 들어오는 간선의 개수는 HashMap으로 구현하였다. 
> 프로그래머스 주사위 고르기 (lv.3) 
기본 로직 자체는 문제에서 주어진 대로 구현하면 된다. 하지만 그대로 풀게 되면 시간 초과가 발생하기 때문에 최적화하는 과정이 필요하다. 
내가 최적화를 진행한 부분은 두 가지이다. 
1. 각 주사위마다 중첩되어 나오는 수를 압축하여 [주사위의 숫자, 나온 횟수] 의 형태로 ArrayList에 담아주었다. 
2. …
> [week11] 황지연

- src/jiyeon/week12/표현 가능한 이진트리.java
- src/jiyeon/week12/［PCCP 기출문제］ 3번 ／ 아날로그 시계.java
- src/jiyeon/week12/［PCCP 기출문제］ 4번 ／ 수식 복원하기.java
> 황지연
> PCCP 기출문제 : 아날로그 시계 
1분에  초침이 한 바퀴 돈다. 그렇기 때문에 일반적인 경우 1분에 시침과 분침을 무조건 한 번 만나기 때문에 기본 횟수를 `(60*h + m) * 2`  로 설정한 후, "일반적이지 않은 경우의 횟수"를 제한다. 
일반적이지 않은 경우는 아래와 같다. 
-  X시 59분 00초부터 59분 59초까지는 절대 분침과 초침이 만나지 않음 
- 11시 59분 -> 12시 0분 이 1분간은 시, 분, 초침이 만나지 않음 -> 그 후 12시 정각에 한 번에 만남 
- 마지막 시점의 시,분,초침의 위치 (시/분침이 초침과 만날 수도 있고 아닐 수도 있기 때문이다.)
> PCCP 기출문제 : 수식 복원하기 
구현문제 이다.  2~9진수 중 어떤 진수의 수식인지 판단하면 된다. 
이를 위해서 알아야 할 기본 개념은 다음과 같다. 
- N진수일 경우 숫자는 0~N-1만으로 표현 할 수 있다. 
=> 예를들어 42라는 숫자가 있을 경우 4진수까지는 이 숫자를 표현 하지 못한다. 왜냐하면 42에서 가장 큰 숫자는 4이기 때문이다. 
- 위 개념을 이용하여 진수의 범위를 줄이고, Integer.toString()의 진수 변환을 이용하여 계산 하면 된다. 
> 표현 가능한 이진트리
포화이진트리의 노드 개수는 2^(d+1) - 1 이다. 
포화이진트리의 최소 노드 개수를 구하고, 개수의 차만큼 앞에 0을 채워넣어 포화이진트리를 완성시킨다. 
그 후 해당 트리가 문제조건을 만족하는지 판단하면 된다.
문제조건을 만족하려면 
- 부모노드가 0인데 자식 노드가 1이면 안된다!
> 다들 …
> [week12] 황지연

- src/jinu/week12/Week12_수식복원하기.java
- src/jinu/week12/Week12_아날로그시계.java
- src/jinu/week12/Week12_표현가능한이진트리.java
> 이진우 
1.문제를 크게 포화 이진트리로 만들기 위한 필요한 0의 개수
2. 0을 붙여서 포화 이진트리로 만드는 부분 
3. 재귀적으로 리프노드에서 루트 노드까지 탐색하며 만들어 질 수 있는 이진트리인지 확인하는 부분
으로 나누었습니다. 
이때 이진트리인지 확인하는 부분은 만일 자식 노드가 1을 포함하고 있는데 그 부모노드가 0을 포함하고 있을 때 이진트리가 아니다 라는 로직을 수행하였습니다. 
1. 문제를 크게 X진법에서 X의 후보가 될 수 있는 부분을 추출하는 부분 
2. X라는 미지수값에 값을 대입하는 부분으로 나누었습니다.
X진법에서 X의 후보가 될 수 있는 부분을 검사하는 로직은 각각의 숫자를 이루고 있는 숫자보다 같거나 작은 진법은 가능한 진법이 아니다 를 수행합니다. 
또한 X라는 미지수값에 값을 대입하는 부분에서는 
첫 번쨰 수와 두 번째 연산 수가 같고 빼기일 때 0 출력
후보가 될 수 있는 진법에서 각각 다른 연산이 나온다면 ? 출력
그렇지 않다면 계산 결과 출력의 로직을 따릅니다. 
저는 이 부분이 어려워서 정답 코드를 참조하였습니다. 
배운 로직의 핵심 부분은 
초침과 분침이 만나 발생하는 알람의 횟수를 구할 때 
초침과 분침이 주기적으로 만나는 1시간을 기준으로 구하며,
초침과 시침이 만나 발생하는 알람의 횟수를 구할 떄는 
초침과 시침이 주기적으로 만나는 12시간을 기준으로 구하는 것입니다. 
하지만 아직 완벽하게 이해는 못한 것 같습니당. 
같이 고민해봐요!..  …
> [Week12] 이진우

- src/minsu/week12/Week12_150367.java
- src/minsu/week12/Week12_250135.java
- src/minsu/week12/Week12_340210.java
> 김민수
> 150367, 표현 가능한 이진트리
해당 주어진 숫자를 이진수로 변환하여 트리 시점으로 봅니다.
포화 이진트리를 일단 만들어야 하기 때문에 포화이진트리가 아니라면 맨 앞에 0을 부족한 만큼 추가해줍니다.
그리고 트리 모양이 형성이 되는지 안되는지 판단하면 됩니다.
> 250135, 시계문제
시간을 1초 단위가 아닌 0.001초 기준으로 완탐을 진행하였습니다.
> 340210 수식 복원하기
2진법 ~ 9진법까지 가능한 진법들을 찾아서
수식 중 X에 들어갈 값을 찾습니다. X에 값을 찾을 때 10진법을 2~9진법으로 변환하고 또 2~9진법을 10진법으로 변환해서
X에 들어 갈 값을 찾습니다.
> [week12] 김민수

- src/jaehyeon/week12/Week12_150367.java
- src/jaehyeon/week12/Week12_250135.java
- src/jaehyeon/week12/Week12_340210.java
> 임재현
> [표현 가능한 이진트리](https://school.programmers.co.kr/learn/courses/30/lessons/150367)
> [수식 복원하기](https://school.programmers.co.kr/learn/courses/30/lessons/340210)
> [아날로그 시계](https://school.programmers.co.kr/learn/courses/30/lessons/250135)
> [week12] 임재현

- src/jinu/week13/Week13_비밀코드해독.java
- src/jinu/week13/Week13_택배배달과수거하기.java
- src/jinu/week13/Week13_홀짝트리.java
> 이진우
1. 백트래킹으로 정답이 가능한 조합을 탐색한다.(정답 조합은 항상 5개의 크기)
2. 정답 조합이 실제로 입력한 정수와 비교하여 일치하는 개수(ans배열)이 동일한지 판단
3. 만약 동일하다면 count(정답) 1 증가 
1. 배달용 집 Stack과 수거용 집 Stack 따로 관리 
2. 배달용 집 peek 거리와 수거용 집 peek 거리 중 큰 값*2 를 정답값에 더함. (이동한 거리이므로)
3. 배달용 집 Stack에서 하나 꺼냄-> 만약 들고온 배달 갯수(capacity)를 다 썼고 아직 그 집에 배달할 물품이 남았다면 다시 stack 저장,
만약 들고온 배달 갯수를 다 쓰지 못했다면 stack에서 계속 꺼냄
4. 수거용 집 Stack 도 동일한 논리 적용 
1. 홀짝 트리인지 판단하는 방법: 
같은 트리 내에서 그룹으로 묶여있는 부분에서 
항상 대상으로 지정한 노드가 루트일 때를 기준으로 홀수 노드 , 짝수 노드 , 역홀수 노드, 역짝수 노드인지 판단한다. 
홀짝 트리가 되려면 : 홀수 노드가 1개(루트 노드) + 나머지 노드가 모드 역홀수 노드 또는 역짝수 노드 + 짝수노드가 (0개) 
또는                         짝수 노드가 1개 (루트 노드) + 나머지 노드가 모두 역홀수 노드 또는 역짝수 노드 + 홀수 노드 (0개)
를 만족해야 한다. 
이번에는 더 어려웠던 것 같슴다.
> [week13] 이진우

- src/jaehyeon/week13/Week13_150369.java
- src/jaehyeon/week13/Week13_388352.java
- src/jaehyeon/week13/Week13_388354.java
> ex) 임재현
> [홀짝 트리](https://school.programmers.co.kr/learn/courses/30/lessons/388354)
> [비밀 코드 해독](https://school.programmers.co.kr/learn/courses/30/lessons/388352)
> [택배 배달과 수거하기](https://school.programmers.co.kr/learn/courses/30/lessons/150369)
> [week13] 임재현

- src/jiyeon/week13/비밀 코드 해독.java
- src/jiyeon/week13/택배 배달과 수거하기.java
- src/jiyeon/week13/홀짝트리.java
> 황지연
> 택배 배달과 수거하기
Greedy 알고리즘으로 풀이하였습니다. 
- pickup을 함께 고려하기 위해서는 최대한 가장 먼 거리를 먼저 가는 것이 좋음 
- 배열을 역순으로 탐색하여 deliveries 배열, pickup 배열 중 가장 먼 배열의 인덱스를 탐색
- visit 메서드를 이용하여 cap 만큼 배달 및 수거 => 반복 
> 비밀 코드 해독
완전 탐색으로 풀이하였습니다. 
기본 로직은 가능한 비밀 코드를 모두 조합하여 ans 배열과 비교하는 것입니다. 
- ans[i]가 0이면 해당 숫자들은 비밀 코드에 절대 포함되지 않고, ans[i]가 5이면 해당 숫자들이 비밀 코드에 해당합니다.
- n의 크기가 커질 수록 ans[i]가 0일 가능성이 높아지기 때문에 숫자 후보 배열에서 제외합니다. 
- 숫자 후보 배열을 좁힌 다음 해당 배열에서 모든 조합 구성 -> 완전 탐색을 통하여 비밀 코드를 찾습니다. 
> 홀짝트리 
각 노드의 요소를 루트 노드라고 가정한 후 트리를 만들어 해당 트리가 홀짝트리 / 역홀짝 트리 인지 판단합니다.  
구체적인 과정은 코드 주석에 달려있습니다. 
> 홀짝트리 넘 어려워요.
> [week13] 황지연

- src/minsu/week13/Week13_150369.java
- src/minsu/week13/Week13_388352.java
- src/minsu/week13/Week13_388354.java
> [week13] 김민수

- src/jaehyeon/week14/Week14_214288.java
- src/jaehyeon/week14/Week14_258707.java
- src/jaehyeon/week14/Week14_92342.java
> 임재현
1️⃣ https://school.programmers.co.kr/learn/courses/30/lessons/92342
2️⃣ https://school.programmers.co.kr/learn/courses/30/lessons/258707
3️⃣ https://school.programmers.co.kr/learn/courses/30/lessons/214288
> [week14] 임재현

- src/jiyeon/week14/n ＋ 1 카드게임.java
- src/jiyeon/week14/상담원 인원.java
- src/jiyeon/week14/양궁대회.java
> 황지연
> 양궁 대회 
1. 비트 마스킹으로 모든 조합을 구한다. (해당하는 점수를 쏜다면 1, 쏘지 않는다면 0)
2. info 배열을 참고하여 해당 조합일 때 라이언이 사용해야하는 `최소 화살 개수(used`)를 구한다. 
3. 만약 used > n 이라면 해당 조합은 가능하지 못하기 때문에 continue
4. used<n 이라면 해당 조합은 가능 && 그리고 가장 낮은 점수에 화살이 많이 맞춰져있는 경우의 수를 구해야하기때문에 n-used 화살은 0점에 몰아서 넣어준다. 
> n+1 카드 게임
그리디 문제이다. 
- 우선순위 1 : 처음에 뽑은 카드 중에서 두 장 내기 
- 우선 순위 2 : 처음에 뽑은 카드 중에서 한 장 내기 + 새로 뽑은 카드 중에서 한 장 내기 (- 코인 1)
- 우선 순위 3 : 새로 뽑은 카드 중에서 두 장 내기 (- 2코인)
주의)) 당장 코인을 내고 가지지 않는 카드라고 해도 미래의 턴을 위해 미리 살 수도 있기 때문에 후보 덱에 포함시켜야함 
코인이 < 0 || 가진 카드(처음에 뽑은 카드 + 새로 뽑은 카드) 중에서 낼 수 없을 때 까지 반복
> 상담원 인원 
1. 먼저 각 유형마다 최소 한 명은 배정해야하기때문에 배정한다. 
2. 각 유형 마다 한 명씩 추가해서 배정한 케이스를 반복하며, 제일 이전과 차이가 큰 유형을 찾아내고, 해당 유형을 증가시킨다. 
3. 2번을 n-k만큼 반복한다.
> [week14] 황지연

- src/minsu/week14/Week14_214288.java
- src/minsu/week14/Week14_258707.java
- src/minsu/week14/Week14_92342.java
> [week14] 김민수

- src/jiyeon/week15/문자열 압축.java
- src/jiyeon/week15/순위 검색.java
- src/jiyeon/week15/자물쇠와 열쇠.java
> 황지연
> 문자열 압축 
> 순위 검색 
> 자물쇠와 열쇠 
자물쇠의 크기를 열쇠 X 2 만큼 확장 
확장된 자물쇠 map 에서 열쇠를 한 칸씩 이동시켜가면서 열쇠가 맞는지 확인한다.
> 순위 검색 넘 어려워요
> [week15] 황지연

- src/jinu/week15/Week15_문자열압축.java
- src/jinu/week15/Week15_순위검색.java
- src/jinu/week15/Week15_자물쇠와열쇠.java
> 이진우 
> 코드 참조 
자물쇠와 열쇠는 아이디어를 참고하였습니다.
> [week15] 이진우

- src/minsu/week16/Week16_13422.java
- src/minsu/week16/Week16_20008.java
- src/minsu/week16/Week16_2987.java
- src/minsu/week8/Week8_17951.java
- src/minsu/week8/Week8_32718.java
> 김민수
> No.2987 사과나무
사과나무 좌표 하나와 삼각형  세 개 좌표에서 두 개 좌표씩 골라 각 세 개의 삼각형 넓이의 합이 원래 삼각형 넓이와 같다면 삼각형 넓이 이내에 있는 것이다.
> No. 13422 도둑
슬라이딩 윈도우와 누적합 두 가지 방법으로 접근해서 풀었습니다.
M이 N이랑 같다면 경우의 수가 answer / 3을 해줘야하는게 중요한 것 같습니다
> No.2008 몬스터를 처치하자!
시간을 기준으로 현재 시간에 쓸 수 있는 스킬들을 쓰면서 깊이 우선 탐색을 진행했습니다.
>
> [week16] 김민수

- src/jinu/week16/Week16_13422.java
- src/jinu/week16/Week16_20008.java
- src/jinu/week16/Week16_2987.java
> 이진우
> 2987 : 사과나무
- 어떤 식으로 접근해야 할 지 감이 잡히지 않아 해답 참조
- CCW 알고리즘 사용 
- 이해될듯 안될듯한 상태 
> 13422 : 도둑
- 초기에 M크기만큼 돈 세팅 
- 이후 기존 sum에서 배열 첫 값 빼주고 추가해야 할 값 더해주는 방식 시도 (일종의 슬라이딩 윈도우?)
- N과 M의 크기가 같을 때는 정답 1로 고정 
> 20008 : 몬스터를 처치하자!
- 몬스터의 체력을 참고하여 백트래킹으로 스킬 순서를 먼저 확정
- 그 순서대로 시간이 얼마나 걸리는지 Map을 활용하여 구하고 지속적으로 최소 시간 갱신
> [week16] 이진우

- src/jiyeon/week16/boj_13422.java
- src/jiyeon/week16/boj_20008.java
- src/jiyeon/week16/boj_2987.java
황지연
> **2987번 사과나무** 
기하학 문제입니다. 
처음에는 두 점을 지나는 직선 방정식을 구해서 풀어야하나? 라는 의문이 들었지만 아무리 시뮬레이션해봐도 로직이 안나와서 결국 30분 정도 고민 후 구글링 했습니다. 
" 한 점에 대하여 만약 삼각형의 두 점과 주어진 점을 이어서 만든 삼각형 3개의 넓이의 합이 원래 삼각형과 같다면 그 점은 삼각형 내부에 있는 점이다. "
라는 개념을 이용하여 문제를 풀이하였습니다. 
</br>
</br>
> **13422번 도둑** 
슬라이딩 윈도우를 이용하여 풀이하였습니다. 
크게 신경 써야하는 부분은 두 가지 입니다. 
- 인덱스(i)가 N-M을 넘어갈 때 
- 처음부터 N==M 일 때
인덱스가 N-M을 넘어갈 때는, 배열이 순환구조이기 때문에 out of range가 아니라 다시 처음으로 돌아가야합니다. 
나름대로 생각을 해서 구현했는데 (분기 방식)
나중에 다른 분들 풀이보니깐 모듈러방식으로 구현하는 좀 더 빨라서 그걸로 변경했습니다. 
그리고 만약 문제에서 N==M으로 주어진다면 한 번만 검사하면 됩니다. 처음에 이걸 생각을 못했습니다. 
</br>
</br>
> **20008번 몬스터를 처치하자!**
백트래킹을 이용한 완전 탐색을 진행하였습니다 
처음에는 그리디 + PriorityQueue를 이용하여 
- 사용 가능한 스킬 큐 
- 대기열 스킬 큐 
로 구분하여 구현하였습니다. 
하지만 예제 3의 경우 그리디로 못푸는 case라서 결국 포기하였습니다.
백준 사이트의 [알고리즘 분류]를 보고 백트래킹 해야한다는 걸 알게되었고 이후 …
> [week16] 황지연

- src/jiyeon/week17/boj_22251.java
- src/jiyeon/week17/boj_2631.java
- src/jiyeon/week17/codetree_여왕개미.java
> 황지연
> [codetree] 여왕개미 
구현 + 이분 탐색 
정찰메서드를 이분탐색으로 풀어야하는지 모르고 시뮬레이션으로 처음에 접근했다가 풀이를 보고 이분탐색인줄 알았다...
그리고 개미집 제거 메서드를 문제를 제대로 안읽고 hard delete로 풀었다. hard delete로 풀면 문제에서 주어지는 인덱스를 사용할 수 없어서 무조건 soft delete로 풀어야한다.
어려운 문제는 아니였는데 문제에서 놓친 부분이 많아 오래 걸렸다. 문제를 잘 읽고 구조화시키는 연습을 해야겠다.
</br>
> 백준 2631번 줄세우기 
문제를 보고 LIS를 이용해서 풀면 된다는 것은 빨리 깨달았는데, dp로 구현하는 로직을 까먹어서 구현하는데 애를 좀 먹은 문제이다. 
최장 수열의 요소의 개수를 구한 다음 전체 요소 개수에서 최장 수열 요소의 개수를 빼면 된다 
</br>
> 백준 22251번 빌런 호석
처음에는 디스플레이 반전 이야기가 나오길래 비트마스킹으로 풀어야하나? 라는 생각이 들었는데 
문제 풀이 로직을 정리해보니 일단 완탐으로 풀어보는게 맞는 거 같아 시도했는데 다행히 잘 맞아떨어졌다 ㅎㅎ
구현하는 건 어렵지 않았다 순열을 이용하여 모든 경우의 수를 탐색하면 된다.
> [week17] 황지연

- src/minsu/week13/Week13_388354.java
- src/minsu/week17/Week17_2631.java
- src/minsu/week17/Week17_여왕개미.java
> 김민수
> 줄세우기
전체 수열 길이에서  가장 긴 증가하는 부분 수열 길이를 빼주면 됩니다.
>  빌런 호석
숫자들을 비트 마스킹을 활용하여 풀었습니다.
>  여왕 개미
정찰 메서드를 이진 탐색으로 활용하여 풀었습니다
>
> [week17] 김민수

- src/jinu/week17/Week17_22251.java
- src/jinu/week17/Week17_2631.java
- src/jinu/week17/Week17_QueenAnt.java
> 이진우
> 백준 2631
- 어떻게 하면 최대한 있는 그대로의 순서를 유지하며 최소한만 바꿀수 있을지 고민 
- 백트래킹이나 완전 탐색은 불가 
- 최장 길이 수열을 구한 후 나머지 부분만 바꾸면 되겠다 생각 
> 백준 22251
- 숫자를 엘리베이터 숫자에 맞게 배열화한 이후 calculateNeedDiff 메서드를 활용하여 특정 숫자에서 특정 숫자로 변경 시 필요한 반전 갯수 저장
- 백트래킹으로 접근 
> Code Tree QueenAnt 
- 명령어인 100, 200 , 300, 400 별로 따로 생각
- 300인 경우 그냥 자바 리스트에서 지울 경우 추후 숫자가 꼬일 수 있음에 유의 
- 벌어질 수 있는 간격의 최대 간격을 이분 탐색의 자료로 활용하여 풀이 
>
> [week17] 이진우

- src/jaehyeon/week18/Week18_2293.java
- src/jaehyeon/week18/Week18_2294.java
- src/jaehyeon/week18/Week18_2616.java
- src/jaehyeon/week18/Week18_Microbe.java
> 임재현
> [소형기관차](https://until.blog/@hyeonzip/-baekjoon--%EC%86%8C%ED%98%95%EA%B8%B0%EA%B4%80)
> [동전 1](https://until.blog/@hyeonzip/-baekjoon--%EB%8F%99%EC%A0%84-1)
> 미생물 연구
>
> [week18] 임재현

- src/jaehyeon/week19/Week19_2011.java
- src/jaehyeon/week19/Week19_20165.java
> 임재현
> [암호코드](https://until.blog/@hyeonzip/-baekjoon--%EC%95%94%ED%98%B8%EC%BD%94%EB%93%9C)
> [인내의 도미노 장인 호석](https://until.blog/@hyeonzip/-baekjoon--%EC%9D%B8%EB%82%B4%EC%9D%98-%EB%8F%84%EB%AF%B8%EB%85%B8-%EC%9E%A5%EC%9D%B8-%ED%98%B8%EC%84%9D)
>
> [week19] 임재현
